### ISSUE TITLE
Version 1.5 corrupts a BTRFS volume

### ISSUE THREAD

**Issue by huaixv** [maharmstone/btrfs#215] opened 2019-11-16 15:30 UTC
I am trying backing up the data and will attach more detailed logs.

**Comment by huaixv** [comment] 2019-11-17 08:53
## Configuration
Disk | Partition | Compression? | Corrupted? | Accessible?
------|-------------|---------------------|-----------------|------------------
SAMSUNG MZNTY256HDHP SSD M2.SATA | /dev/sda2 | lzo | Yes |  WinBtrfs and `ro,nologreplay` under Linux
HGST HTS541010B7E610 HDD SATA | /dev/sdb1 | lzo | No | Both WinBtrfs and Linux

Thank you @magsom for the mount option

## Recovery
First mount the partition with `ro,nologreplay` mount option.
Then `rsync` can be used to backup to the data to a safe place.
In the `ro` case, `btrfs send` cannot be used to backup the partition unless there is already a recent read-only snapshot of subvolumes.
I was unable to recover the partition from the corruption (using `btrfs rescue` or `btrfs check`).
So the easiest way is to reformat the partition.
`mkfs.btrfs -m dup` may help prevent further problems (See #161 for details, I have not tested it yet)

## Actions done before the corruption
No explicit write operation is performed on the partition.
I just have a look at the btrfs tab in the properties dialog.

## Symptoms
- The partition will not mount under Linux unless `ro,nologreplay` is used either:
    - explicitly : via the mount option
    - implicitly : boot the system from the partition

- However the partition is always accessible from WinBtrfs under Windows

## mount output
```
# mount /mnt/data/sda2.img -t btrfs /mnt/root                                                                                                 
mount: /mnt/root: can't read superblock on /dev/loop0.
```
## dmesg output
```
[    5.208170] Btrfs loaded, crc32c=crc32c-intel
[    5.211270] BTRFS: device fsid 45d1a4ad-3446-4625-b1bc-58361b35c838 devid 1 transid 567070 /dev/sda2
[    5.215138] BTRFS: device label DATA devid 1 transid 246989 /dev/sdb1
[   54.795315] BTRFS info (device sda2): disk space caching is enabled
[   54.795320] BTRFS info (device sda2): has skinny extents
[   54.851628] BTRFS info (device sda2): enabling ssd optimizations
[   54.862317] BTRFS error (device sda2): bad tree block start, want 10059776 have 0
[   54.862442] BTRFS: error (device sda2) in __btrfs_free_extent:4860: errno=-5 IO failure
[   54.862541] BTRFS: error (device sda2) in btrfs_run_delayed_refs:2795: errno=-5 IO failure
[   54.862634] BTRFS: error (device sda2) in btrfs_replay_log:2321: errno=-5 IO failure (Failed to recover log tree)
[   54.935302] BTRFS error (device sda2): open_ctree failed
[   78.496911] BTRFS info (device sda2): trying to use backup root at mount time
[   78.496916] BTRFS info (device sda2): disk space caching is enabled
[   78.496919] BTRFS info (device sda2): has skinny extents
[   78.543166] BTRFS info (device sda2): enabling ssd optimizations
[   78.547556] BTRFS error (device sda2): bad tree block start, want 10059776 have 0
[   78.547583] BTRFS: error (device sda2) in __btrfs_free_extent:4860: errno=-5 IO failure
[   78.547606] BTRFS: error (device sda2) in btrfs_run_delayed_refs:2795: errno=-5 IO failure
[   78.547640] BTRFS: error (device sda2) in btrfs_replay_log:2321: errno=-5 IO failure (Failed to recover log tree)
[   78.601920] BTRFS error (device sda2): open_ctree failed
[   87.041820] BTRFS info (device sda2): allowing degraded mounts
[   87.041825] BTRFS info (device sda2): disk space caching is enabled
[   87.041828] BTRFS info (device sda2): has skinny extents
[   87.103973] BTRFS info (device sda2): enabling ssd optimizations
[   87.114228] BTRFS error (device sda2): bad tree block start, want 10059776 have 0
[   87.114325] BTRFS: error (device sda2) in __btrfs_free_extent:4860: errno=-5 IO failure
[   87.114414] BTRFS: error (device sda2) in btrfs_run_delayed_refs:2795: errno=-5 IO failure
[   87.114497] BTRFS: error (device sda2) in btrfs_replay_log:2321: errno=-5 IO failure (Failed to recover log tree)
[   87.156708] BTRFS error (device sda2): open_ctree failed
```

## btrfs utilities output
- btrfs rescue super-recover
```
All supers are valid, no need to recover
```
- btrfs rescue zero-log (Core Dumped)
```
Clearing log on sda2.img, previous log_root 22298624, level 0
checksum verify failed on 10059776 found 000000B6 wanted 00000000
checksum verify failed on 10059776 found 000000B6 wanted 00000000
bad tree block 10059776, bytenr mismatch, want=10059776, have=0
...... (Same as three lines above)
btrfs unable to find ref byte nr 152846336 parent 0 root 2  owner 0 offset 0
path->slots[0]: 0 path->nodes[0]:
fish: Job 2, 'sudo btrfs rescue zero-log sda2…' terminated by signal SIGSEGV (Address boundary error)
```
- btrfs rescue chunk-recover
```
......
ERROR: attempt to start transaction over already running one
extent buffer leak: start 22036480 len 16384
WARNING: dirty eb leak (aborted trans): start 22036480 len 16384
extent buffer leak: start 22069248 len 16384
WARNING: dirty eb leak (aborted trans): start 22069248 len 16384
extent buffer leak: start 133215289344 len 16384
WARNING: dirty eb leak (aborted trans): start 133215289344 len 16384
extent buffer leak: start 22298624 len 16384
WARNING: dirty eb leak (aborted trans): start 22298624 len 16384
extent buffer leak: start 22347776 len 16384
WARNING: dirty eb leak (aborted trans): start 22347776 len 16384
extent buffer leak: start 22020096 len 16384
WARNING: dirty eb leak (aborted trans): start 22020096 len 16384
Chunk tree recovered successfully
```
Full output available [here](https://paste.ubuntu.com/p/5xBPt7Hrk5/)

- btrfs-find-root
```
Superblock thinks the generation is 567070
Superblock thinks the level is 1
Found tree root at 1095630848 gen 567070 level 1
Well block 150093824(gen: 567068 level: 1) seems good, but generation/level doesn't match, want gen: 567070 level: 1
...... (Similar output omitted)
Well block 906805248(gen: 567040 level: 0) seems good, but generation/level doesn't match, want gen: 567070 level: 1
...... (Similar output omitted)
Well block 963395584(gen: 565297 level: 0) seems good, but generation/level doesn't match, want gen: 567070 level: 1
```
Almost none of these found roots can help in `btrfs check`, see details below
- btrfs check (directly)
```
Opening filesystem to check...
Checking filesystem on /mnt/data/sda2.img
UUID: 45d1a4ad-3446-4625-b1bc-58361b35c838
[1/7] checking root items
checksum verify failed on 10059776 found 000000B6 wanted 00000000
checksum verify failed on 10059776 found 000000B6 wanted 00000000
bad tree block 10059776, bytenr mismatch, want=10059776, have=0
ERROR: failed to repair root items: Input/output 
```
-  btrfs check -r 150093824
```
Opening filesystem to check...
parent transid verify failed on 150093824 wanted 567070 found 567068
parent transid verify failed on 150093824 wanted 567070 found 567068
Ignoring transid failure
checksum verify failed on 74579968 found 000000B6 wanted 00000000
checksum verify failed on 74579968 found 000000B6 wanted 00000000
bad tree block 74579968, bytenr mismatch, want=74579968, have=0
ERROR: cannot open file system
```
- btrfs check -r 963395584
```
Opening filesystem to check...
parent transid verify failed on 963395584 wanted 567070 found 565297
parent transid verify failed on 963395584 wanted 567070 found 565297
Ignoring transid failure
parent transid verify failed on 955957248 wanted 565297 found 566058
parent transid verify failed on 955957248 wanted 565297 found 566058
Ignoring transid failure
parent transid verify failed on 247824384 wanted 565122 found 566896
parent transid verify failed on 247824384 wanted 565122 found 566896
Ignoring transid failure
parent transid verify failed on 950009856 wanted 565297 found 566056
parent transid verify failed on 950009856 wanted 565297 found 566056
Ignoring transid failure
parent transid verify failed on 939278336 wanted 565292 found 566051
parent transid verify failed on 939278336 wanted 565292 found 566051
Ignoring transid failure
Checking filesystem on /mnt/data/sda2.img
UUID: 45d1a4ad-3446-4625-b1bc-58361b35c838
[1/7] checking root items
Error: could not find extent items for root 259
ERROR: failed to repair root items: No such file or directory
```
- btrfs inspect-internal dump-tree -t 1
```
btrfs-progs v5.3.1 
root tree
node 1095630848 level 1 items 6 free 487 generation 567070 owner ROOT_TREE
fs uuid 45d1a4ad-3446-4625-b1bc-58361b35c838
chunk uuid 56dc612f-c1b4-43cd-8344-dc4951aa3974
	key (EXTENT_TREE ROOT_ITEM 0) block 1095647232 gen 567070
	key (298 INODE_ITEM 0) block 152551424 gen 567070
	key (339 INODE_ITEM 0) block 152731648 gen 567070
	key (399 ROOT_REF 3932) block 1095663616 gen 567070
	key (3944 ROOT_BACKREF 399) block 134317998080 gen 566724
	key (3971 ROOT_ITEM 566724) block 152420352 gen 567070
leaf 1095647232 items 97 free space 2050 generation 567070 owner ROOT_TREE
leaf 1095647232 flags 0x1(WRITTEN) backref revision 1
fs uuid 45d1a4ad-3446-4625-b1bc-58361b35c838
chunk uuid 56dc612f-c1b4-43cd-8344-dc4951aa3974
	item 0 key (EXTENT_TREE ROOT_ITEM 0) itemoff 15844 itemsize 439
		generation 567070 root_dirid 0 bytenr 1095729152 level 2 refs 1
		lastsnap 0 byte_limit 0 bytes_used 146472960 flags 0x0(none)
		uuid 00000000-0000-0000-0000-000000000000
		drop key (0 UNKNOWN.0 0) level 0
	item 1 key (DEV_TREE ROOT_ITEM 0) itemoff 15405 itemsize 439
		generation 567041 root_dirid 0 bytenr 85639168 level 0 refs 1
		lastsnap 0 byte_limit 0 bytes_used 16384 flags 0x0(none)
		uuid 00000000-0000-0000-0000-000000000000
		drop key (0 UNKNOWN.0 0) level 0
	item 2 key (FS_TREE INODE_REF 6) itemoff 15388 itemsize 17
		index 0 namelen 7 name: default
	item 3 key (FS_TREE ROOT_ITEM 0) itemoff 14949 itemsize 439
		generation 463228 root_dirid 256 bytenr 156862152704 level 0 refs 1
		lastsnap 0 byte_limit 0 bytes_used 16384 flags 0x0(none)
		uuid c1fbb1b1-5dab-4eaf-bb2f-8bd6bda118d0
		ctransid 463228 otransid 0 stransid 0 rtransid 0
		ctime 1570415008.241841613 (2019-10-07 10:23:28)
		otime 1553584720.0 (2019-03-26 15:18:40)
		drop key (0 UNKNOWN.0 0) level 0
......
```
Full output available [here](https://paste.ubuntu.com/p/QWGmFGqS3z/)

## WinBtrfs debug output
I installed the dubug build of version and set `DebugLogLevel` to `3` and keep `LogFile` the default value but there is no output in the `DebugView` and the `C:\btrfs.log` file is not created.
I will try to reinstall the driver sometime later.

## Reproducibility
Not tested yet, I will update the comment when tests are done.
But this problem seems similar to issue #161 

If there is any other logs that can help investigate the problem, please let me know and I'll do my best to help.

**Comment by maharmstone** [comment] 2019-11-17 12:19
Thanks, that's a great help. I agree, it's more than likely the same issue as 161 - a corruption issue seemingly only affecting SSDs, that I've not been able to replicate.

At present we ignore the transaction log, because I've never been able to cajole Linux into a situation where it'd create one - it looks like this might be the root of the problem.

One workaround for the time being would be to make sure SSDs are unmounted cleanly on Linux before rebooting into Windows; as I understand it, the log should be cleared if this is the case.

**Comment by Alumniminium** [comment] 2019-12-17 22:22
jesus christ why isnt this more visible... i just had to edit a file real quick and didn't want to create a liveusb, now my entire parition is fucked and I gotta reinstall. 

`It ought to be suitable for day-to-day use, but make sure you take backups anyway.` 

multiple open issues that it corrupts the parition...

**Comment by deadair3210** [comment] 2019-12-17 23:36
Ought to ≠ ready for production

**Comment by SleeplessSloth** [comment] 2020-01-21 23:12
I have the same issue right now with the same error, what can I do to provide some more debug info before I reformat the partition?

Some more info:
I have an SSD (Samsung Evo 750) btrfs partition and an HDD (WD Blue) btrfs partition. Only the SSD one is affected. I've already reformated the drive before since I thought it was btrfs doing it's thing but the problem is the same as here, so it's most probably the same issue.

dmesg from a live iso:
```
[  491.379089] BTRFS error (device sda1): bad tree block start, want 5914624 have 0
[  491.379109] BTRFS: error (device sda1) in btrfs_run_delayed_refs:2188: errno=-5 IO failure
[  491.379109] BTRFS info (device sda1): forced readonly
```
Some things are different from the OP though. zero-logging the drive fixes the issue temporarily, so I'm able to run a scrub, here's the log:

```
Jan 21 23:07:08 manjaro kernel: BTRFS warning (device sda1): checksum error at logical 5914624 on dev /dev/sda1, physical 5914624: metadata leaf (level 0) in tree 2
Jan 21 23:07:08 manjaro kernel: BTRFS error (device sda1): bdev /dev/sda1 errs: wr 0, rd 0, flush 0, corrupt 1, gen 0
Jan 21 23:07:08 manjaro kernel: BTRFS error (device sda1): unable to fixup (regular) error at logical 5914624 on dev /dev/sda1
```

**Comment by hedgepigdaniel** [comment] 2020-01-27 23:06
> Thanks, that's a great help. I agree, it's more than likely the same issue as 161 - a corruption issue seemingly only affecting SSDs, that I've not been able to replicate.
> 
> At present we ignore the transaction log, because I've never been able to cajole Linux into a situation where it'd create one - it looks like this might be the root of the problem.
> 
> One workaround for the time being would be to make sure SSDs are unmounted cleanly on Linux before rebooting into Windows; as I understand it, the log should be cleared if this is the case.

Perhaps then a good path forward would be to publish a patch that refuses to mount if the transaction log is not empty. If this problem can't be reproduced after that, then the theory is confirmed.

In the meantime, it's pretty unfair/innaccurate to have this driver published and say that it works well enough for normal use, when it is clearly corrupting people's filesystems. Would it really be amiss to add a message in the README pointing out that this bug exists, and using the driver on a M.2/mSATA SSD is likely to corrupt the filesystem?

**Comment by maharmstone** [comment] 2020-01-27 23:48
The recent patches should fix this issue.

**Comment by hedgepigdaniel** [comment] 2020-01-28 00:17
Good to hear. What was the fix?

**Comment by maharmstone** [comment] 2020-01-28 00:27
https://github.com/maharmstone/btrfs/commit/12b95ba18bd5b39e3291b3f6799396d4e0cfcce4

**Comment by hedgepigdaniel** [comment] 2020-01-28 00:32
Are there risks there - e.g. is there a possibility of losing recently written data if the transaction log is cleared?

**Comment by SleeplessSloth** [comment] 2020-01-28 00:33
Interesting why mounting with a dirty log would only damage SSDs. Gonna take a backup and test the fix soon, big thanks!

**Comment by maharmstone** [comment] 2020-01-28 00:38
@hedgepigdaniel - Yes, but that's a risk inherent in shutting down without unmounting, and on Btrfs in particular. The worst case scenario is that you lose 30 seconds' worth of work. The net effect is that files opened with O_SYNC on Linux will be treated as if they haven't been, but I'm not sure what opens files like this anyway (databases?).

@SleeplessSloth - I was wondering that. My guess is either that there's something in Linux which only creates logs on SSDs, or that the caching on HDDs means that logs never get flushed before the commit.

**Comment by SleeplessSloth** [comment] 2020-01-28 01:06
Quick question: what does the linux btrfs driver do when it encounters the same situation? Does it clear the log, too?

**Comment by maharmstone** [comment] 2020-01-28 01:20
No, it replays it. This is a quick fix to prevent corruption, a full implementation will hopefully follow in a future version. There's no practical drawbacks to this feature not being implemented, it only affects files opened in a certain way on Linux.

**Comment by noradtux** [comment] 2020-01-28 08:30
As for the difference between SSD and HDD, by default new btrfs filesystems are created with metadata=single on SSD and metadata=DUP on HDD. I forced a filesystem on the SSD to metadata=DUP and left one with metadata=single; on the same SSD. The one with metadata=single was corrupted, the one with metadata=DUP is fine.

**Comment by buster** [comment] 2020-04-22 17:44
After investing hours why my linux partition is fucked, i've come across this bug report.
The biggest question for me is: Is there a way to fix the partition?
I'm using Debian and suddenly Debian stopped working. Unable to boot.
I was able to mount the filesystem with SystemrescueCd...
It contains some Windows Folders like "System Volume Information" in the root (besides /usr, /home, etc.).
Now i have some hope to get the filesystem working again, but how (besides copying the files and reinstalling).

**Comment by SleeplessSloth** [comment] 2020-04-22 22:20
There's no way to actually fix the partition that I'm aware of but I've had great luck with `btrfs restore`. I just copied all my files from my SSD to my HDD, reformated the SSD, and copied them back

**Comment by hedgepigdaniel** [comment] 2020-04-23 11:52
My advice:
1. Do not use btrfsck
1. Do not try to fix the broken partition
1. Make a backup in the simplest way possible, e.g. with dd
1. As @SleeplessSloth said, its usually possible to mount it read only, and create a new partition with the files.

**Comment by maharmstone** [comment] 2020-07-01 08:04
Closed as no longer an issue.

**Closed by maharmstone** 2020-07-01 08:04 UTC
