### ISSUE TITLE
Unusual behavior in file properties with GIT

### ISSUE THREAD

**Issue by BakasuraRCE** [maharmstone/btrfs#79] opened 2018-01-09 17:29 UTC
I am currently working on a GIT repository located on the btrfs disk. There is no problem until I try to add changes and create a commit in the repository:

```
git init
# add some changes ...
git add .
```

I get this error:

> Rename from '.git/objects/08/tmp_obj_...' to '.git/objects/08/778d7a8....' failed. Should I try again? (y/n)

Problem that does not appear when I'm working with any disc with a normal Windows format.

I researched this error and found nothing, so I decided to go to the GIT source code

Specifically, these two lines create the file indicated in the error:

https://github.com/git-for-windows/git/blob/a56c4f9e2a9513d2be57dc4346e0e84887399cd9/sha1_file.c#L1529

https://github.com/git-for-windows/git/blob/a56c4f9e2a9513d2be57dc4346e0e84887399cd9/sha1_file.c#L1546

The problem is that the file is created with the property "Only Read" when working on the btrfs disk, then when the program tries to rename the file or move it, its access is denied. Another point to keep in mind is that if I decide to give "No" to the error, the program is able to delete the temporary file.

My temporary solution was to patch the binary to establish the creation permissions in "0644" (octal), and it works perfectly.

Respect to this issue, I was not sure where I should go, but get to put it here as it only happens with this driver. Please correct me if this is incorrect.

**Comment by maharmstone** [comment] 2018-01-14 03:11
Thank you, that's a remarkably detailed error report!

Yes, you're quite right - the problem is that the driver isn't allowing a readonly file to be renamed, when apparently it should. I'll look into it.

If you're using Windows 10, a workaround is to use the version of Git which comes with Ubuntu on Windows - that worked fine for me.

**Comment by maharmstone** [comment] 2018-01-25 20:21
This should be fixed by https://github.com/maharmstone/btrfs/commit/2bae497857a09f977dc35fab067bc0a6a85595c5

**Closed** 2018-11-20 23:54 UTC
