### ISSUE TITLE
Visual Studio, Adding a folder to a project that is located on a BTRFS drive creates a folder with "Foldername\" in the name

### ISSUE THREAD

**Issue by MaxineAnne** [maharmstone/btrfs#341] opened 2021-01-13 03:17 UTC
Prerequisites:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎12/‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0
btrfs driver 1.7.5

Application:
Visual Studio

Steps to reproduce:
1.  In a Project in visual studio, add a new folder & hit enter to create the folder.
![image](https://user-images.githubusercontent.com/7060299/104401823-f9047500-5522-11eb-96ee-382bf6501254.png)
![image](https://user-images.githubusercontent.com/7060299/104401835-fd309280-5522-11eb-8b99-a4debaadc2ec.png)
![image](https://user-images.githubusercontent.com/7060299/104401844-ff92ec80-5522-11eb-9d09-3fa447a0fe7b.png)
![image](https://user-images.githubusercontent.com/7060299/104401846-015cb000-5523-11eb-9af9-9ccdf366707f.png)
![image](https://user-images.githubusercontent.com/7060299/104401848-03bf0a00-5523-11eb-94ef-4e57449c2073.png)
![image](https://user-images.githubusercontent.com/7060299/104401850-04f03700-5523-11eb-81a6-96e367a15e90.png)

This folder does indeed have the '\' character in the name and cannot be deleted in windows and requires booting into Linux to delete the folder in question:
![image](https://user-images.githubusercontent.com/7060299/104402035-62848380-5523-11eb-9fcb-d24a50481ea5.png)

*I have reported this bug to the Visual Studio Authors as well.*

**Comment by maharmstone** [comment] 2021-01-13 08:18
Duplicate of https://github.com/maharmstone/btrfs/issues/337.

**Closed by maharmstone** 2021-01-13 08:18 UTC

**Comment by maharmstone** [comment] 2021-01-14 04:12
Fixed in v1.7.6
