### ISSUE TITLE
WinBtrfs 1.3 corrupts a filesystem without me doing anything to it (happened twice in a row)

### ISSUE THREAD

**Issue by intelfx** [maharmstone/btrfs#161] opened 2019-06-25 08:21 UTC
I have a Btrfs filesystem that I decided to mount using WinBtrfs 1.3 in Windows 10 1809.

* I mounted the filesystem (which mounted a non-top-level subvolume `/arch` by default),
* then decided to snapshot a nested subvolume (`/arch/home`, or `/home` relative to the mountpoint), which thrown a "CRC error"
* at this point the filesystem turned read-only and I got a non-zero amount of "corruptions" in device stats
* after a reboot, the filesystem was rendered un-mountable both in WinBtrfs and in Linux:

```
# mount -o ro,norecovery work-1.img /mnt/work
mount: /mnt/work: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.

# dmesg
<...>
[35448.836533] BTRFS: device label linux devid 1 transid 843713 /dev/loop0
[35448.837376] BTRFS info (device loop0): disabling log replay at mount time
[35448.837379] BTRFS info (device loop0): using free space tree
[35448.837380] BTRFS info (device loop0): has skinny extents
[35448.972688] BTRFS error (device loop0): bad tree block start, want 854474752 have 0
[35448.972705] BTRFS warning (device loop0): failed to read root (objectid=10): -5
[35448.990657] BTRFS error (device loop0): open_ctree failed
```

```
# mount -o ro,norecovery,usebackuproot work-1.img /mnt/work
mount: /mnt/work: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.

/mnt/d2/2019-06-25 root@stratofortress
# dmesg
<...>
[35521.508093] BTRFS info (device loop0): disabling log replay at mount time
[35521.508096] BTRFS info (device loop0): trying to use backup root at mount time
[35521.508097] BTRFS info (device loop0): using free space tree
[35521.508098] BTRFS info (device loop0): has skinny extents
[35521.509365] BTRFS error (device loop0): bad tree block start, want 854474752 have 0
[35521.509385] BTRFS warning (device loop0): failed to read root (objectid=10): -5
[35521.509414] BTRFS error (device loop0): bad tree block start, want 854474752 have 0
[35521.509422] BTRFS warning (device loop0): failed to read root (objectid=10): -5
[35521.509850] BTRFS error (device loop0): bad tree block start, want 850116608 have 0
[35521.509863] BTRFS error (device loop0): bad tree block start, want 850051072 have 0
[35521.509877] BTRFS error (device loop0): failed to read block groups: -5
[35521.530403] BTRFS error (device loop0): open_ctree failed
```

I will provide any further logs and dumps if you need them.

**Comment by maharmstone** [comment] 2019-06-26 07:56
Thanks. Could you paste the output of `btrfs inspect-internal dump-tree -t 1 /dev/loop0` please?

**Comment by intelfx** [comment] 2019-06-26 08:16
Technically current btrfs-progs fail early when free space cache (objectid=10) is damaged and don't do anything at all:
```
$ btrfs inspect-internal dump-tree -t 1 pristine.img
btrfs-progs v5.1.1
checksum verify failed on 854474752 found E4E3BDB6 wanted 00000000
checksum verify failed on 854474752 found E4E3BDB6 wanted 00000000
bad tree block 854474752, bytenr mismatch, want=854474752, have=0
Couldn't read free space tree
ERROR: unable to open pristine.img
```
With this patch (https://github.com/intelfx/btrfs-progs/commit/6953db9ae4c34541b892f01f13586823850c6a49) applied however it is possible to read the root tree: http://ix.io/1MPc

**Comment by intelfx** [comment] 2019-06-28 12:39
Note that the issue with free space tree is not the only one. The extent tree got broken as well:

```
# btrfs check --repair work.img
enabling repair mode
Opening filesystem to check...
checksum verify failed on 48600940544 found E4E3BDB6 wanted 00000000
checksum verify failed on 48600940544 found E4E3BDB6 wanted 00000000
bad tree block 48600940544, bytenr mismatch, want=48600940544, have=0
Couldn't read free space tree
checksum verify failed on 48566599680 found E4E3BDB6 wanted 00000000
checksum verify failed on 48566599680 found E4E3BDB6 wanted 00000000
bad tree block 48566599680, bytenr mismatch, want=48566599680, have=0
Couldn't read block groups
ERROR: cannot open file system
```

With a few more patches (https://github.com/intelfx/btrfs-progs/commit/66c26afc72390aa16b312f2a3edb30c7162c62dc + everything in that branch) I hacked up btrfs-progs to "disable" free space tree (i. e. simply unset the superblock bit as to not confuse other tools; I wasn't able to make it remove the root tree item itself):

```
# btrfs check --repair --init-extent-tree --clear-space-cache v2 work.img
enabling repair mode
Opening filesystem to check...
checksum verify failed on 48600940544 found E4E3BDB6 wanted 00000000
checksum verify failed on 48600940544 found E4E3BDB6 wanted 00000000
bad tree block 48600940544, bytenr mismatch, want=48600940544, have=0
Couldn't read free space tree
Checking filesystem on work.img
UUID: d648c0d1-8423-4985-ae59-1716a8966741
Clear free space cache v2
XXX: btrfs_clear_free_space_tree: free_space_root not present, doing black magic
free space cache v2 cleared
```

And then partially repair the extent tree: http://ix.io/1N0h

This was enough to make the filesystem RO-mountable again, although with messed up space accounting.

**Comment by intelfx** [comment] 2019-06-28 12:41
@maharmstone Also it would seem that this corruption is reproducible, i. e. after I recreated the filesystem and booted into Windows again it broke the new filesystem as well, even without me doing anything (so the title is misleading, it's not required to snapshot anything for this to happen).

**Comment by danyi-david** [comment] 2019-07-14 21:12
This happened to me before. No snapshots or anything special, I just added a new SSD to my system, partitioned the drive into one partition, formatted it under linux, then booted into windows.

I decided to copy world of warcraft onto the new partition, and around mid-way the operation just hung, and the whole drive was corrupted.

Re-formatted the partition, copied the files onto it under linux, game was working under wine. Rebooted into windows, started the game, it actually worked for a while, but soon the drive was corrupted again.

I gave up on experimenting at that point, and decided to partition the drive into two partitions, so I use half of it under linux with btrfs, and the other half formatted to ntfs under windows. Works fine, so there is no problem with the drive itself.

This was happening with Windows 10 1809 and winbtrfs 1.2, I didn't try it ever since.

**Comment by hedgepigdaniel** [comment] 2019-08-04 00:12
I just experienced a very similar set of symptoms., The end result seems to be that my filesystem is completely unreadable (I proceeded to run `btrfs check` with more options to try to make it mount as writable).

Maybe this warrants a loud warning in the README, or a default read only mode on installation? This is quite a large problem!

In case it helps, I was deleting a large number of small files from windows when the deletion process hung. When I restarted, the filesystem was unmountable. I was using zstd compression.

**Comment by maharmstone** [comment] 2019-08-04 12:11
I've still not been able to reproduce this, unfortunately...

@hedgepigdaniel - are you definitely using the most recent version, 1.3? What version of Windows are you using?

**Comment by hedgepigdaniel** [comment] 2019-08-08 13:31
Yes - I had just done all the windows updates and installed the latest winbtrfs 1.3.

Possibly relevant information:
* Dell XPS 9560, Toshiba THNSN5512GPUK NVMe TOSHIBA 512GB
* linux 5.2.5 If I remember right
* zstd compression enabled in (linux) mount options
* I use https://github.com/markfasheh/duperemove every so often to save space

3 large directories with many small files were being deleted in windows at once. All three hung (the progress indicators got stuck and stopped updating). I eventually cut the power. This was the first time that I had consiously changed the contents of my BTRFS partition from windows (although I know windows does wriets on its own, e.g. the `$RECYCLEBIN` etc.

**Comment by maharmstone** [comment] 2019-08-11 12:31
Thanks. Given that you're using NVMe, I wonder if the issue is to do with TRIM support? That'd certainly explain why the issue affects some people but not others.

I've just amended the readme to add the undocumented `NoTrim` option. Can you please set that to 1, and see if you still get your problem?

**Comment by tytgatlieven** [comment] 2019-09-01 18:32
Hi all
@maharmstone:

Could it be that the issue is related to disabled windows fast boot?
I also keep haveing fs errors after schutting down Windows and going to Linux. Nothing really special About my setup.
2 SSD discs, zstd compression, btrfs on secondary SSD, root subvolume mounted.

Tonight I noticed that fastboot is disabled in my machine. Perhaps this changes something in the shutdown routines you depend on?

Hope this helps you one step forward.

Anyway: Marveleous work you are doing! My deepest respect!

Kind regard

Lieven

**Comment by maharmstone** [comment] 2019-09-01 18:41
Thank you. I always disable Fast Boot, so I don't think it's that (unfortunately)...

My working assumption at the moment is that it's something to do with TRIM - either some drives have a quirky implementation, or there's something wrong somehow in how we're doing it. Have you tried the `NoTrim` option I described in my last post?

**Comment by ale5000-git** [comment] 2019-09-01 18:50
@tytgatlieven: Usually it is the opposite, having fast boot enabled is more likely to cause problem in some circumstances.

**Comment by tytgatlieven** [comment] 2019-10-08 13:39
I do not seem to have any issues anymore when using winbtrfs 1.4

No idea if this is due to using 1.4, or something else has changed (on the linux side)
Perhaps this problem is only triggered when a fs already has some error in it before being mounted in windows?

**Comment by noradtux** [comment] 2019-10-09 15:23
Had this happen to two partitions on a SSD using winbtrfs 1.4. Surprinsingly the partition on the HD is fine. So the theory regarding TRIM sound sensible to me.

**Comment by SergeGautherie** [comment] 2019-10-09 16:50
@intelfx, did you too file this issue with regard to a SSD?

**Comment by noradtux** [comment] 2019-10-09 17:58
One other difference apart from TRIM is that HD get metadata=DUP while SSDs get metadata=single. Disabling trim didn't seem to help. Now I created my filesystems with metadata=dup. Let's see what happens.

**Comment by magsom** [comment] 2019-10-25 06:01
My configuration:
- btrfs partition metadata single on a USB SSD
- WinBtrfs 1.4 and Windows 10 18990
After a failed USB safe ejection and a normal shutdown on Windows, I boot Linux 5.3.6 and find the btrfs become read-only. 
btrfs check seems same as original poster:
[1/7] checking root items
checksum verify failed on 123456 found E4E3BDB6 wanted 00000000
checksum verify failed on 123456 found E4E3BDB6 wanted 00000000
bad tree block 123456 bytenr mismatch, want=123456, have=0
ERROR:failed to repair root items: Input/output error

I don't know how to repair btrfs.

**Comment by intelfx** [comment] 2019-10-25 09:08
@magsom It isn't easy to repair btrfs after this corruption. Look for my replies above; I hacked up various patches against btrfs-progs that allow to repair btrfs to the point of salvaging data (you will still need to recreate the whole filesystem afterwards).

**Comment by intelfx** [comment] 2019-10-25 09:08
@SergeGautherie Yes, that's an SSD.

**Comment by SergeGautherie** [comment] 2019-10-25 13:09
> Yes, that's an SSD.

Then, everyone has SSD/NVMe, which confirms Mark's clue.

--

> SSDs get metadata=single

Would a HD with forced metadata=single allow to reproduce?

**Comment by intelfx** [comment] 2019-10-25 13:12
@SergeGautherie I'll try to find some time to make backups and attempt to controlled reproduce the bug this evening.

**Comment by ale5000-git** [comment] 2019-11-11 08:20
@intelfx: Have you tried with version 1.5?

**Comment by SleeplessSloth** [comment] 2020-01-27 23:19
Seems like #215 is the same issue, I believe it'd be easier to navigate/provide more info if we combined them.

P.S. I have an image of the corrupted btrfs partition(took one before I reformated it), I can provide any info I can to help fix the bug. [More info](https://github.com/maharmstone/btrfs/issues/215#issuecomment-576930618)

**Comment by ale5000-git** [comment] 2020-03-03 16:07
Does it still happens with the latest version?

**Comment by tnilzon** [comment] 2020-07-01 07:38
As a user I must ask a very important question to the developer: Is this now tested and verified safe and not causing any btrfs file system corruption (also safe on ssd disks)? I have had numerous of issues with corrupted btrfs volumes on ssd with this in the past, forcing me to reformat. So, is the latest version now safe to use?

**Comment by damian101** [comment] 2020-07-01 07:51
@tnilzon The issue should be fixed since version 1.6, it was mentioned in #215. 
I actually used WinBtrfs on Btrfs on an SSD with some 1.7 version for a few months and didn't have any issues during that time.

**Comment by tnilzon** [comment] 2020-07-01 07:53
OK, thanks for a very fast reply :-)
I will download and update to the latest version (1.7.3) then!

**Comment by damian101** [comment] 2020-07-01 07:56
@tnilzon Just to be clear, I'm not the developer, maharmstone is :)

**Comment by maharmstone** [comment] 2020-07-01 08:03
@tnilzon - yes, I'm fairly sure this is fixed, and should be closed.

**Closed by maharmstone** 2020-07-01 08:03 UTC

**Comment by tnilzon** [comment] 2020-07-01 08:16
Oh, **damian101** but thanks for sharing the information then ;-)

And many thanks to **@maharmstone** for fixing this issue (I feel safe now) !
