### ISSUE TITLE
Version 1.7.2 causes Windows Defender to pop up trojan warning

### ISSUE THREAD

**Issue by h-vetinari** [maharmstone/btrfs#254] opened 2020-04-19 19:20 UTC
Hi, thanks a lot for this piece of software!

I wanted to install it and downloaded the last release from github. I saw the warning that the release might not satisfy the more onerous signing requirements of recent windows versions, but I was quite surprised to see the following warning from windows defender upon unpacking:

![btrfs_trojan_warning](https://user-images.githubusercontent.com/33685575/79697486-65e42a80-8283-11ea-907d-051564b8d974.PNG)

I'm on 
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
```
which is (AFAICT) the most recent version available through normal windows upgrade on my machine.

**Comment by maharmstone** [comment] 2020-04-19 19:22
This is a false positive, i.e. a load of cobblers. Duplicate of https://github.com/maharmstone/btrfs/issues/252.

**Closed by maharmstone** 2020-04-19 19:22 UTC

**Comment by h-vetinari** [comment] 2020-04-19 19:24
Ok, sorry for the noise. Might still be useful to mention this in the README?

At the very least, it's quite a bit more drastic than an unsigned installer.

**Comment by maharmstone** [comment] 2020-04-19 19:26
Are your Windows Defender definitions definitely up to date? I couldn't reproduce this when I tried - I'm wondering if Microsoft have fixed their mistake.

**Comment by h-vetinari** [comment] 2020-04-19 19:38
Unfortunately, yes:
![defender_definition](https://user-images.githubusercontent.com/33685575/79697970-0d625c80-8286-11ea-99c2-f6ac0fefea62.png)

**Comment by h-vetinari** [comment] 2020-04-19 19:41
I thought I'd just move to chocolatey, but alas:
![choco_install](https://user-images.githubusercontent.com/33685575/79698044-88c40e00-8286-11ea-9e13-293e3eea687e.png)

**Comment by maharmstone** [comment] 2020-04-19 19:46
Hmm. I think the only way around it is to disable Windows Defender and use something decent, which is frustrating. I'll add something to the README.

**Comment by h-vetinari** [comment] 2020-04-19 20:11
Sorry to be annoying, but considering the severity of the warning, could you at least provide expected sha-hashes of the files for the last version? Or a GPG signature?

**Comment by maharmstone** [comment] 2020-04-19 20:15
SHA-256:

```
80d0756f74b165da17ef0baa51f993a9829cb7c337e69d4880328ba9570a52e3  ./Debug/x86/btrfs.sys
db6348ee5cbb13b255649df6d85265595335d58a66a24cf8526b2638027ab553  ./Debug/x86/shellbtrfs.dll
2237b320288dd7baefe11da07a3a4f93181f4759c598dfa8653564c13daa49eb  ./Debug/x86/ubtrfs.dll
0fa85aa143ebe444d03d700dd388dacb471206554a552eb77bc88065b9234da8  ./Debug/x86/mkbtrfs.exe
a109e99a1628b0c0975728ec1ebcc2190d1ed1a93dbfd6c729e1ead20c2111bb  ./Debug/arm/btrfs.sys
a20fae3d58d2fbf8dae7b4fbf216386e463af83071d5c6f1d9402d504ce04dd1  ./Debug/arm/mkbtrfs.exe
0ec821b9997af29324bfecb9fd963fb086771db559fd18a8663fd7cf5ba30857  ./Debug/arm/shellbtrfs.dll
55b5ec9818de3c58097b9c4c7924898cc46ea283f5312a2f81496ecdc4e38984  ./Debug/arm/ubtrfs.dll
edb3b5f8015e38a9bf94e9c1c7fc42f26e4ffdeb2d681041e743325102d84774  ./Debug/aarch64/btrfs.sys
b1776d33f5ba10fbf36fcf1fe33601dec9ed9b3f0bcd967040de2c6db5ad25a0  ./Debug/aarch64/shellbtrfs.dll
7e1ff815cd4786d6101aeeacadaf0a54087ee3b61f77305517f6eafe16a932f9  ./Debug/aarch64/ubtrfs.dll
8402b4c61e19d8a5dd670c1c4e82d63500b9a872ac64a988df7dadb3685de184  ./Debug/aarch64/mkbtrfs.exe
a7a09fff80c679dbb54df4c93710e8dddb0542c1d71d011c35d80ca2b638b881  ./Debug/x64/mkbtrfs.exe
b1f372433071bcfc6a100a552f509e4b1840c0669ddd044df71086f03605c58c  ./Debug/x64/shellbtrfs.dll
8828eea24d1624304dd13c69018114b95c77c7dcc3d2373bd0acade246084303  ./Debug/x64/ubtrfs.dll
57f3cebdd8c4e464b00ee2940d7733cee0168a1e13d5e30c582cf6072d701a3b  ./Debug/x64/btrfs.sys
313cac73f600ecadcf62c85a283b8d92e6afa780b2387eba99e3f8cfcafa5351  ./Debug/btrfs.inf
f370c12f6554e7e0bb7e36b67c87679b2875d01c4dd8154e0116fcf5d48fbda6  ./Debug/btrfs.cat
d1e713b3a8e437709ad5012166c81e9a0dd28b0604b9f49156c23b35cb6266f7  ./Release/x86/btrfs.sys
b3651aedf55eabc7914361973cd6a73e93feb01c3bcddaba06f098860df63775  ./Release/x86/shellbtrfs.dll
efe6ac13db49e24808220b46519e5eff888660d7ac8270fda209fb10aab9b86f  ./Release/x86/ubtrfs.dll
223f8e0749ed836d17c6e336693bf0bcd9a1bb725e0e5b9e6176c8523d9b64ba  ./Release/x86/mkbtrfs.exe
d87b828117295123716160afe7169a2e8b00b3564131a177ff2a38c09357dba1  ./Release/x86/mkbtrfs-stripped.exe
b0b7082ffc02bea6d4b212ad6e8a89e537cdb6c9e523b48a3c6a389bfbca002e  ./Release/arm/btrfs.sys
bc81aaab562bf86efc3beead1eb4c675f87e13ce527b5066a021c655314ccd6c  ./Release/arm/mkbtrfs.exe
87f885958a94207037b3efae6be89c073e0421aef587441c13053e32b9c1943d  ./Release/arm/shellbtrfs.dll
2ad82801f3b43336f4059a977724a4a37cfcb9c395d3b0929d8ed7e5c1d76536  ./Release/arm/ubtrfs.dll
c0b2c0bf6ffe32876ff9226c3d1bfcf62dfa0b80d498471f9dba40654f4a57dc  ./Release/aarch64/btrfs.sys
b9cae3930fe9442614901bab1c9972a7acb065e67314fa1d90728bc2aae076e9  ./Release/aarch64/shellbtrfs.dll
e8a54394f3bbf921433b86d2082617e979a010f0fc383b7827cb43d7fe1a2564  ./Release/aarch64/ubtrfs.dll
6cfc1460bc38bd92d9b3b8c8a4e9e3612ba3a543a05a8febe56783c032e416a8  ./Release/aarch64/mkbtrfs.exe
6e58b181a69a9934c55d906e39f666f3b2af9da7f534bee42335983b7e6a073d  ./Release/x64/btrfs.sys
cfed9c093d33d029b68715236dd5e819cac0bf44015722371d38744a7d2f3a01  ./Release/x64/mkbtrfs.exe
fef87bcf3b2cd11990cb35b64934183d571adf1be7bd54f79f10ab54a0391506  ./Release/x64/shellbtrfs.dll
5c554dee760bf877e635f8741fbdce292d49735ae9c3bb104778c01bf9c86c17  ./Release/x64/ubtrfs.dll
313cac73f600ecadcf62c85a283b8d92e6afa780b2387eba99e3f8cfcafa5351  ./Release/btrfs.inf
835ac9d203e2c6b445c6ef21730e6b33e0179fff28fba39c4bf0feae73887adf  ./Release/btrfs.cat
af60f998d6a4a3025310677a5899daf831a9c3063dfd65fd66224a2488252f4c  ./pdb/Debug/x86/btrfs.pdb
870cc340c68521874aa2be3cf37e34c9d3cbe49fae3a9828a13b2c0801e47d8e  ./pdb/Debug/x86/mkbtrfs.pdb
27428cec24263f40fe520fabdbd5e025ffcd266aa63ab81a153789a0de4f210a  ./pdb/Debug/x86/shellbtrfs.pdb
b49d95278669e866ed980207e8df8aca1728c9f768abebe82547249249025db3  ./pdb/Debug/x86/ubtrfs.pdb
44d0be3a85dd894cddfd6e5e92749e8698baf2b50d65c3e00ab372ed63338714  ./pdb/Debug/x64/btrfs.pdb
df3c863fe1cbe040f4fc536acbda63fa95b783564d14ffb2efd224ea9a200ad2  ./pdb/Debug/x64/mkbtrfs.pdb
50d1ece2746a7561ceeb488b26802da75397c5538e455758d04d3ec1278fb6a3  ./pdb/Debug/x64/shellbtrfs.pdb
56914839066abdb64627922a8ee757b6f96246ec264492fd54465499893172e3  ./pdb/Debug/x64/ubtrfs.pdb
8dc6d82a5c52726a325058387d6c0a82c92a7cb8f3d1dfaeb224bd17ac064f44  ./pdb/Debug/arm/btrfs.pdb
8db7fc260e0b17e83c228ed40fb177090566951b0386231b0961fbc6014b85c8  ./pdb/Debug/arm/mkbtrfs.pdb
199a14127df03028003a390df57a9ae8748fcd55fade36acaf94060837577316  ./pdb/Debug/arm/shellbtrfs.pdb
a972f2d508815079deed3916a5a2c5190db003885093a7283a2ebaa5d8401cc9  ./pdb/Debug/arm/ubtrfs.pdb
5be597e775e0ef53a1e97df20d3a8bcfa70c844efbc6b7949ce707f56f352a0a  ./pdb/Debug/aarch64/btrfs.pdb
3e5872ab2dcf06cd11b6e6210ba61814162fcbc3f849f756a19c55b641145c64  ./pdb/Debug/aarch64/mkbtrfs.pdb
981ab205f9ab3e0a05cfb99afead1ecf4c73a36427e79830107ce8f0c5bd145d  ./pdb/Debug/aarch64/shellbtrfs.pdb
bc50c6d0bd7f79d7ac19198ad39d7ba7b404aa6d7ce1efc8f9f766576642d919  ./pdb/Debug/aarch64/ubtrfs.pdb
cda849d50c5ea2c2a23dcd16b7388f9a98ac8a3aa1740a759b53e4815b650679  ./pdb/Release/aarch64/btrfs.pdb
5df3eda31e3cf6af2d4f2918ca3e614b7bf5d8e11be686f1bc1ef7b02eb62c56  ./pdb/Release/aarch64/mkbtrfs.pdb
8e225cd26fd6f0e825888e7fc468732c2360a506f26a126feece72c2bdf533f2  ./pdb/Release/aarch64/shellbtrfs.pdb
0dcc41acfa0a8cf05995d0babc0ddbae7f6576b2a69ac261fcbe0d7b4b781e6f  ./pdb/Release/aarch64/ubtrfs.pdb
2ed25958feb34cbbcfde347b6898de3769d23f95c911d3a81cd0668e598b0b55  ./pdb/Release/arm/btrfs.pdb
dd22e9d70fda63afb4bad2d097b0d201a6bce02528abf0f2a47c8b26c867aa16  ./pdb/Release/arm/mkbtrfs.pdb
2333f5447e288e906eab85ba7f905b01102b04acc56e0073832ca02842e61066  ./pdb/Release/arm/shellbtrfs.pdb
e2830332e5c8a12e80c0a4ebaf769dae46ba5d9f5ea5b8b38e7c5f58e20cac36  ./pdb/Release/arm/ubtrfs.pdb
cedd9ac6a72242d53718003a3bc1e263eb7903935313deeaa94edd7fd6e372e5  ./pdb/Release/x64/btrfs.pdb
3c0655324581a3eca16cc5544bdd79e3920eab11470a882710144fba3bb92531  ./pdb/Release/x64/mkbtrfs.pdb
42978b8152202875cec0e4964d20e82940e6abcfd20bcefe9112d196204fd05a  ./pdb/Release/x64/shellbtrfs.pdb
7b18d914e8a03eee919f5e0f540b67d48b630f71da59fd8956926e1feb6e232d  ./pdb/Release/x64/ubtrfs.pdb
f690ab84ac361ab31856a5f310bf3ef80e04376f3075fe81debe4e45a13bd06d  ./pdb/Release/x86/btrfs.pdb
2ed4ab429a98da663c9ca80ff1aaea34c8e1f306c02800d2c9398e6e8445db91  ./pdb/Release/x86/mkbtrfs.pdb
d899eff7ddc1f73aba8bb17e02723e79a5cb835fb01b1dfdabe9e486238f89e8  ./pdb/Release/x86/shellbtrfs.pdb
247f47a85d80a059b91b3803d3b6e75557f3576b90fbca3a0f0dac5639332919  ./pdb/Release/x86/ubtrfs.pdb
9c48cd30330dbe603108449bac9ab9d192d52326583c27eb1c47071c0ba7dd65  ./btrfs-1.7.2.zip
f56385ceae72a1092a231cf6b6e4c5e1542e05981e5f2ff081c39e830b52757a  ./btrfs-1.7.2-debug.zip
d3fbb43f9d25ff2950fa3aa0b80cc0cfc831f63fc9d64b93cea921d01439c7a5  ./btrfs-1.7.2-pdb.zip
```

**Comment by h-vetinari** [comment] 2020-04-19 20:21
Thanks a lot!

**Comment by SergeGautherie** [comment] 2020-04-19 22:48
For the record:
#252: `Trojan:Script/Wacatac.C!ml`
#254: `Trojan:Win32/Wacatac.D!ml`
