### ISSUE TITLE
Error 0x800704b3 when opening .exe files

### ISSUE THREAD

**Issue by csolisr** [maharmstone/btrfs#519] opened 2022-08-30 18:09 UTC
Whenever I download an executable file (such as an installer) into a Btrfs-formatted folder on Windows 11, and attempt to open the file, the following error message appears:

```
Windows could not gain access to {file}
Error code: 0x800704b3
The network path was either typed incorrectly, does not exist, or the network provider is not currently available. Please try retyping the path or contact your network administrator.
```

Furthermore, when right-clicking on the item, the "Btrfs properties" tab does not appear, although it does appear on other files in the same folder. Booting to Linux and manually setting the user and permissions for the file there fixes the issue. Moving the file to a drive formatted with another file system, such as NTFS, also solves the error. Is there some setting I can use to fix the permissions set by Windows?

**Comment by maharmstone** [comment] 2022-08-30 18:20
800704b3 corresponds to ERROR_NO_NET_OR_BAD_PATH. Is this a normal drive or a network share?

Also, could you please give me the exact version of Windows you're on? `winver` will tell you.

**Comment by csolisr** [comment] 2022-08-30 21:02
This is a normal drive, a partition of a physical NVME drive. `winver` is 21H2 (build 22000.918)

**Comment by maharmstone** [comment] 2022-08-30 21:14
Is this a preview version or not? I can't make head nor tail of the versioning system nowadays... There's no such issue on 10.0.22000.194.

**Comment by csolisr** [comment] 2022-08-30 21:20
From what I can gather I am on the stable version of Windows 11.

**Comment by 13xforever** [comment] 2022-08-31 18:37
I have the same issue, _some_ executables fail to launch. I do have btrfs tab in file properties though.

In btrfs log there are lines corresponding to the attempts:
```
FFFFE0886CBA2080:fsctl_request:unknown control code 903bc (DeviceType = 9, Access = 0, Function = ef, Method = 0)
```

So far all executables produced by cheat engine exhibit this issue.

**Comment by csolisr** [comment] 2022-08-31 19:26
Not sure if it's relevant, but so far all of my errors involve downloading .exe installer files with Firefox (installed from the Microsoft Store) that require elevated rights to install. Normal .exe files that don't involve elevated rights, and installers in other formats (such as .msi) don't seem to trigger the error.

**Comment by 13xforever** [comment] 2022-08-31 19:29
Yes, I can confirm that all exes I have trouble with have manifest to require elevated context.

**Comment by maharmstone** [comment] 2022-09-05 22:53
It looks like they've changed how UAC works in Windows 11.

This error message is the same as the one that used to be given on previous versions of Windows, before I worked round it. The gist of it was that mpr.dll was checking if the volume was a network filesystem in a broken way, by checking if its type was "NTFS" or "FAT". It was 100% a Microsoft bug, but the workaround was to lie to the OS if it thought it was being called from mpr.dll (see the function `lie_about_fs_type`).

It might be that they've renamed mpr.dll, or moved the offending function to another DLL.

**Comment by Tjalfi** [comment] 2022-09-19 20:58
This problem is not limited to Windows 11, I've got the same problem on Windows 10 21H2 (Build 19043.1889)

**Comment by SunnyRaj84348** [comment] 2022-09-21 12:09
Start WebClient service to fix that issue.
Better to autostart the service at boot.

**Comment by Tjalfi** [comment] 2022-09-22 12:47
That did the trick for me, thank you!

**Comment by lesderid** [comment] 2022-09-22 15:45
> > Start WebClient service to fix that issue. Better to autostart the service at boot.
> 
> I tried finding that service in my device, and I'm not sure if it's because my OS language is Spanish, but I haven't found it under that name or its direct translation. Could you please post the full name of the service you activated?

According to https://www.microsoft.com/en-us/language/Search?&searchTerm=WebClient&langID=736&Source=true&productid=0 it should be 'Cliente web'. You could also try `sc config WebClient start= auto` in an administrative command prompt.

**Comment by jarrard** [comment] 2022-10-01 23:22
> Start WebClient service to fix that issue. Better to autostart the service at boot.

This appeared to have worked for me. Odd that it needs webclient...but such is windows11....

**Comment by dausruddin** [comment] 2022-10-09 04:54
I am having the same issue on 22H2 (Build 22621.608) and the [workaround](https://github.com/maharmstone/btrfs/issues/519#issuecomment-1253615994) worked.

This is how you run WebClient.

1. Run `services.msc`.
2. Scroll until you found WebClient.
3. Start it.
4. You can also enable it to run at boot from Right Click > Properties.

**Comment by Kenst1092** [comment] 2022-12-04 16:33
The workaround works just fine in Windows 10 22H2 build 19045.2006 as well. I couldn't run apps on btrfs drives as Administrator beforehand

**Comment by maharmstone** [comment] 2022-12-21 00:25
This should be fixed by https://github.com/maharmstone/btrfs/commit/5c0a346e2edc8cd5e8be47625bad924afbd977e8

**Closed by maharmstone** 2022-12-21 00:25 UTC

**Comment by adrianinsaval** [comment] 2023-01-02 00:44
when can we expect a release with the fix included?

**Comment by maharmstone** [comment] 2023-01-10 21:29
@adrianinsaval Now
