### ISSUE TITLE
Issues with compression on large files?

### ISSUE THREAD

**Issue by AWiederin** [maharmstone/btrfs#318] opened 2020-11-02 00:27 UTC
I tried to install Dragon Age: Inquisition on my zstd-enabled BTRFS drive, but it kept failing with write or read errors. Process Monitor showed `c00000e5` error codes for each, for ~130MB files.

Installing and enabling debug gave `zstd_decompress:ZSTD_decompressStream failed: Unknown frame descriptor` for read, though I wasn't able to get anything for writes. Switching to zlib gave `zlib_decompress:inflate returned -3` instead, and again only reads.

After disabling compression and deleting the files it seemed to download fine, but then at the "verification" step twice in a row I got a BSOD, the first of which produced this minidump: [110120-12703-01.zip](https://github.com/maharmstone/btrfs/files/5472109/110120-12703-01.zip)

I'm on Windows build 2004 right now, with release 1.7.5.

**Comment by maharmstone** [comment] 2020-11-08 16:27
Thanks for reporting this - I've not seen this before. I'll try to reproduce it.

The crash was a self-induced crash, because it thought it was about to corrupt the filesystem. Does `btrfs check` show anything?

**Comment by AWiederin** [comment] 2020-11-12 02:52
The title is probably wrong, I don't think it's actually compression related, sorry.
I also forgot to mention that this is partition is inside a Veracrypt container.

There were a bunch of csum errors that I *thought* I had already fixed, so I deleted those files and restored almost all of them from a backup. I also ran scrub and `--repair` in Windows and linux, though it required `--clear-space-cache v1` to get rid of all the errors.
However, when redownloading some of the remaining them, I noticed the integrity check afterwards showing corruption just like before, so I started another `btrfs check`:
```
btrfs: csum mismatch on free space cache
failed to load free space cache for block group 26864517120
mirror 1 bytenr 4255989760 csum 164 expected csum 128
```

Followed by many more csum errors. Most of these corrupted files seem to be ones unrelated to anything modified while in Windows, though some *were* copied from a backup while in Windows.

I don't really have a free drive to test from scratch on, sorry.

**Comment by maharmstone** [comment] 2020-11-13 00:52
Okay, thank you - that makes it a little less confusing.

I'm going to close this as I suspect it's an issue with Veracrypt - my hunch is that it's modifying our buffers while we're still checksumming them, though I couldn't see anything obvious in the source code. Please reopen this if you manage to reproduce it without Veracrypt.

If I were you, I'd also do a full SMART test of your drive, just to make sure you don't have any hardware issues.

**Closed by maharmstone** 2020-11-13 00:52 UTC
