### ISSUE TITLE
CrystalDiskMark reports bad write speeds

### ISSUE THREAD

**Issue by TurkeyMan** [maharmstone/btrfs#529] opened 2022-11-08 08:34 UTC
I tested the FS speed to see if it was okay to use for my user partitions generally, rather than just for accessing the linux fs.
I determined that there is a huge perf gap, so I guess we can't use this generally yet.

Any idea why such huge perf gap? Can this be improved, or is it just a symptom of running FUSE-like fs on Windows?

Same physical disk, 2 partitions.
![image](https://user-images.githubusercontent.com/1146706/200513989-11212fbe-65f7-42a7-85bd-b463928d1319.png)

**Comment by maharmstone** [comment] 2022-11-08 23:36
This has come up before, and I think I concluded that CrystalDiskMark wasn't particularly useful or representative for copy-on-write filesystems. But unfortunately I don't think there's anything else.

> is it just a symptom of running FUSE-like fs on Windows?

This is a normal kernel-mode filesystem driver, not a FUSE-like.

**Comment by maharmstone** [comment] 2022-11-09 01:44
The RND4K tests are slow because it creates files with thousands of extents, and the driver spends most of its time looping through these. But such files don't tend to occur outside of tests; I could speed this up, but at the cost of increasing RAM usage for everyday usage, which I think would be counter-productive.

> In your general experience, how does your fs compare to NTFS as baseline?

Copying large files maxes out at more or less the disk write speed, and copying directories is about the same as NTFS. So probably about comparable, though I don't have any hard or fast figures.

Rather than worrying about artificial tests, you're best off trying out the FS, and logging issues if you discover anything that's notably slower on Btrfs than NTFS.

**Comment by TurkeyMan** [comment] 2022-11-09 02:18
> I could speed this up, but at the cost of increasing RAM usage for everyday usage, which I think would be counter-productive.

I dunno. I think most modern users would trade RAM for FS perf. Compiling immediately comes to mind; something I do every few minutes which writes hundreds or thousands of tiny files extremely quickly. Is this pattern subject to the same bottleneck you describe?

My feeling is that copying large files is not really a very interesting performance task. I'm generally much more interested in performance involving many tiny files.

> Rather than worrying about artificial tests, you're best off trying out the FS, and logging issues if you discover anything that's notably slower on Btrfs than NTFS.

Sure, I'll keep this in mind. But it's probably worth not totally dismissing benchmark tests; they may act as a sort of course-grained filter for people coming to your project, and may also be the foundation for disinformation. For instance; rather than posting and asking you here, I might have created a blog post or spread information on reddit or wherever that btrfs on windows is useless because it's much too slow to take seriously...
If I were you, I'd consider it of at least medium importance.

**Comment by Masamune3210** [comment] 2022-11-09 03:05
Trust me, in a world where programs regularly gobble up GB's of ram to do basic things, we don't need a driver taking up more memory than it should just to fix a edge case that is so unlikely to occur that most people just ignore the results

**Comment by TurkeyMan** [comment] 2022-11-09 04:50
So your opinion is that typical high-frequency small file spamming will not be a particular problem, it's just CrystalMark leaning into some pathological case?

**Comment by Masamune3210** [comment] 2022-11-09 21:00
If people are smart enough to install a filesystem driver and to compile software, they are hopefully also smart enough to look at prior issue reports and to not make assumptions about things.

**Comment by maharmstone** [comment] 2022-11-10 00:49
> Compiling immediately comes to mind; something I do every few minutes which writes hundreds or thousands of tiny files extremely quickly. Is this pattern subject to the same bottleneck you describe?

No, quite the opposite: the issue is with large, heavily fragmented files.

Anyway, I'm closing the issue, as this is a WONTFIX.

**Closed by maharmstone** 2022-11-10 00:49 UTC

**Comment by TurkeyMan** [comment] 2022-11-10 09:09
I understand you won't fix it, but I'd still like to understand it.
The tests shown above that suffer the most are random 4k writes. How does that test expose a weakness with large heavily fragmented files? Is the description of the test not actually what it does?
