### ISSUE TITLE
text files compress bug

### ISSUE THREAD

**Issue by Artofeel** [maharmstone/btrfs#277] opened 2020-06-28 11:31 UTC
when editing and saving text files on compressed volume (LZO), sometime btrfs adds additional zeros to the end of file.
Up to 4k (sectorsize?)

Win10.1909
Notepad++ 7.8.6 x32

![btrfs_text_compress_bug](https://user-images.githubusercontent.com/8319507/85946269-bc917300-b95c-11ea-960c-c0b441283c8d.png)

**Comment by maharmstone** [comment] 2020-06-28 11:53
Thanks. I can't reproduce this. Have you changed any of the default settings at all? An 18-byte file is normally written inline, and won't be compressed at all.

If you go to the "Btrfs properties" tab of the properties sheet, what does the "Size on disk" popup say?

**Comment by Artofeel** [comment] 2020-06-28 17:40
yea, I tweak FlushInterval, and maybe something else..
will try to reproduce it with default setting later
I just need to delete all in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\btrfs
and btrfs driver will recreate it again? or I need to reinstall?
![btrfs_text_compress_bug2](https://user-images.githubusercontent.com/8319507/85954349-44dd3b80-b990-11ea-97fd-caaec738e257.png)
![btrfs_text_compress_bug3](https://user-images.githubusercontent.com/8319507/85954351-47d82c00-b990-11ea-8e92-b1ea501a4ff3.png)

**Comment by maharmstone** [comment] 2020-06-28 18:44
I was asking for your settings so that I could try to reproduce it; I don't think changing them will fix your problem.

Is it possible that the driver was interrupted while writing the file - say, Windows crashed, or you removed your drive?

**Comment by Artofeel** [comment] 2020-06-29 05:27
no, it's happened in real time, no crash or drive remove
I just edit > save > edit > save
for test example it's happened on 3-4 save (not at first)

**Comment by AWiederin** [comment] 2020-07-01 00:51
I can confirm this happening to me as well, though I have it set to use zstd instead of zlib. (And it's inside a VeraCrypt container if that matters.)

**Comment by maharmstone** [comment] 2020-07-01 08:08
@AWiederin Thanks. Using Notepad++ as well, or something else?

**Comment by AWiederin** [comment] 2020-07-01 16:34
@maharmstone I actually first encountered it with a code file rsync'd from another drive, when it failed to compile. This was in an MSYS2 environment if it matters.
I think I did see it happen once when saving a file in Sublime Text 3 too, in normal Windows.

**Comment by Artofeel** [comment] 2020-07-04 06:17
it seems happen when you delete something in file
so I'm run some test and yes in 99% it happen when I'm deleting line(s) in text file
so making "data" less trigger this bug for me

**Comment by Artofeel** [comment] 2020-08-27 08:48
it still persist on v1.7.4
just opened already bugged file, deleted NUL line, save, re-open and get new NUL line

**Comment by Artofeel** [comment] 2020-08-27 09:11
here I make a small disk with this bug
you can mount it and try to reproduce it
del NUL > save > re-open
[btrfs-text-bug-test.zip](https://github.com/maharmstone/btrfs/files/5135372/btrfs-text-bug-test.zip)

**Comment by maharmstone** [comment] 2020-09-28 23:26
Sorry @Artofeel, I never responded - thank you for the image, it helped a lot with understanding what was going on.

I suspect this bug may be fixed by https://github.com/maharmstone/btrfs/commit/56b5ba700443490bab526523407e7dec8ff5bb73.

**Comment by Artofeel** [comment] 2020-11-12 09:46
just confirming that issue is gone on v1.7.5
although you need to rewrite file (copy back-to-back \ recompress back-to-back \ etc)
just deleting NULs and re-saving is not enough

**Comment by maharmstone** [comment] 2023-11-30 01:44
Closing old issues

**Closed by maharmstone** 2023-11-30 01:44 UTC
