### ISSUE TITLE
ReactOS Stage 1 install regressed recently

### ISSUE THREAD

**Issue by SergeGautherie** [maharmstone/btrfs#206] opened 2019-11-04 05:15 UTC
reactos-bootcd-0.4.14-dev-172-g6889cff-x86-gcc-lin-dbg + upstream WinBtrfs v1.4:
Stage 1 succeeds.

--

reactos-bootcd-0.4.14-dev-172-g6889cff-x86-gcc-lin-dbg + a WinBtrfs built on 2019.11.02:
"1st" regression:
```
(ntoskrnl/po/poshtdwn.c:259)        SMSS.EXE is still RUNNING (00000054)
WARNING:  MiShutdownSystem at ntoskrnl/mm/shutdown.c:37 is UNIMPLEMENTED!

*** Fatal System Error: 0x00000050
                       (0xE10F9120,0x00000000,0xFD8B49C2,0x00000000)

Driver at fault: 

***     btrfs.sys - Address FD8B49C2 base at FD899000, DateStamp 5db90293
```

--

reactos-bootcd-0.4.14-dev-172-g6889cff-x86-gcc-lin-dbg + a WinBtrfs build on 853914fbc20c0ca6518f88ad7b6d17b27f18b9ec
reactos-bootcd-0.4.14-dev-225-g93220e2-x86-gcc-lin-dbg + a WinBtrfs build on 853914fbc20c0ca6518f88ad7b6d17b27f18b9ec
"2nd" regression:
```
(drivers/storage/scsiport/scsiport.c:2894)   unknown ioctl code: 0x2D1400
(base/setup/lib/utils/filesup.c:274) NtOpenFile failed: c0000034, \Device\CdRom0\reactos\system32\kdvbox.dll
(base/setup/usetup/usetup.c:4069) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\kdvbox.dll' (error 0xc0000034), skipping it...
// As usual until here, then unexpected failures!
(base/setup/usetup/spapisup/cabinet.c:1091) NtCreateSection failed for \Device\Harddisk0\Partition1\ReactOS\bin\AHKAppTests.cmd: c0000020
(base/setup/usetup/usetup.c:4069) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\bin\AHKAppTests.cmd' (error 0xc0000001), skipping it...
(base/setup/usetup/spapisup/cabinet.c:1091) NtCreateSection failed for \Device\Harddisk0\Partition1\ReactOS\bin\regtest.cmd: c0000020
(base/setup/usetup/usetup.c:4069) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\bin\regtest.cmd' (error 0xc0000001), skipping it...
// Same for "all" other files...
```

--

I could do a bisect "later", if needed.

**Comment by maharmstone** [comment] 2019-11-04 08:59
Hi Serge,

I'm closing this because ReactOS is an unsupported platform. If you can reproduce the issues on Windows, I'll reopen it.

**Closed by maharmstone** 2019-11-04 08:59 UTC

**Comment by SergeGautherie** [comment] 2019-11-06 00:29
> *** Fatal System Error: 0x00000050

Sometimes, I get a '0x00000139' instead.

--

1st/"Shutdown" regression was caused by e9ee080cf4413e4bcc7c35f13aa3d3cb41306d0a (init_cache).
Could you double-check what is happening? Thanks.

--

NB:
Reverting "STATUS_END_OF_FILE" helps.
Reverting "init_cache" too does not help.
Then, currently, last usable commit for ReactOS Stage 1 is 2f5a5ac4f46c5c94d3dfcf647c46be452e80a491.
@HeisSpiter, could you too have a glance at these two failures? Thanks.

**Comment by maharmstone** [comment] 2019-11-06 00:34
Serge - I'm sympathetic, but I repeat what I said above: this is a Windows driver that ReactOS happens to use. Please move any discussion to the ReactOS pages unless you can reproduce the issues on Windows.

**Comment by SergeGautherie** [comment] 2019-11-09 08:18
2nd/"Copy files" regression was fixed by 9b156a1e55ebb53c4f223527ba75fac07852385d (`STATUS_END_OF_FILE` revert), obviously :-)

1st/"Shutdown" regression was fixed by some later commit between that one and 27f3bfb7c6f72836e5bcd889a30d5fc5a29e909a :-)

Fixed, thanks!

--

> Please move any discussion to the ReactOS pages unless you can reproduce the issues on Windows.

I understand, but:
* these regressions are WinBtrfs issues, as far as I can tell.
* ReactOS is the only checked build(s) I have to test on.

**Comment by maharmstone** [comment] 2019-11-09 12:14
I'm not aware of any easily available checked builds for Windows - I test against the released versions.

**Comment by MegaZeroX10** [comment] 2019-11-09 20:49
@SergeGautherie It is possible to use Freeldr to boot Windows 2003 and Vista using ReactOS' FreeLDR. There's just no tutorial available that explains how to do it.

**Comment by SergeGautherie** [comment] 2019-11-09 21:15
@MegaZeroX10, I know that. This issue is about installing (= set up), not booting.

**Comment by ale5000-git** [comment] 2019-11-09 22:00
I remember someone mentioning replacing ntfs.sys driver with the WinBtrfs driver inside the Windows installation media, probably you also need to format the partition before install Windows.

I have never tried though.

**Comment by maharmstone** [comment] 2019-11-09 22:01
Clever. I'd be shocked if it worked, though!
