### ISSUE TITLE
Errorcode: 0x800704b3

### ISSUE THREAD

**Issue by CountZ74** [maharmstone/btrfs#542] opened 2022-12-24 14:17 UTC
Hi,

I often get this error in Win11 with files downloaded from the internet. All my library folders are located on the BTRFS drive(s). The error does not come up with all files and sometimes it helps to delete the file and download it again.

**Comment by maharmstone** [comment] 2022-12-24 14:19
This is a duplicate of https://github.com/maharmstone/btrfs/issues/519, which is fixed in the next version.

**Closed by maharmstone** 2022-12-24 14:19 UTC
