### ISSUE TITLE
Debug version of winbtrfs 1.8.1 hangs the system on btrfs volume mount

### ISSUE THREAD

**Issue by 13xforever** [maharmstone/btrfs#516] opened 2022-08-28 11:13 UTC
After installing debug version of btrfs the system becomes completely unresponsive as soon as it detects btrfs volume.

In attached log is captured when I have formatted ntfs drive to btrfs.
One hang after hard reset.
And another system boot after re-formatting the volume under linux (in case there was a problem with windows version of mkbtrfs).

[btrfs_mount_hang.log](https://github.com/maharmstone/btrfs/files/9439528/btrfs_mount_hang.log)

I'm on Windows 11 Pro for Workstations 22H2 (22621.457).
Regular version of the driver works fine for this scenario.

**Comment by maharmstone** [comment] 2022-08-28 11:39
I'm closing this, but only because you're using a pre-release version of Windows. Please re-open it you can reproduce it on another version, or if it still persists when 22H2 comes out properly.

**Closed by maharmstone** 2022-08-28 11:39 UTC

**Comment by 13xforever** [comment] 2022-08-28 11:53
😹everyone will get this build in a month or two, it's been out of proper insider builds since june (when it started getting regular retail CUs)

**Comment by maharmstone** [comment] 2022-08-28 12:15
The quality of the pre-release builds is pretty ropey - I suspect they don't test them to the same degree. I've had a dozens of bugs logged that have magically resolved themselves when the release version rolled round.
