### ISSUE TITLE
Games Crash, or don't launch

### ISSUE THREAD

**Issue by Chaython** [maharmstone/btrfs#261] opened 2020-05-23 08:40 UTC
Total War Games crash after Splash, likely an issue of their engine and nothing you can do about it. {(but you've done amazing at wrapping other things)
Obviously a niche of a niche.
Games Tested:
Total War Warhammer [Crash after spalsh]
Total War Three Kingdoms [Crash after spalsh]
Rome Total War Gold [Steam Hung - Crashed btrfs - explorer - system - after reboot the game dir became 0bytes, no files written - launched steam it recovered the files immediately - opened game dir, files written, bytes accurate, explorer hangs - btrfs crash - system hangs - reset, delete download folder/acf files as to not get stuck in btrfs crash loop] 
They work when installed on other partitions. Sega support was of no help at all[as expected]. 
On a side note first copy attempt via steam [move game from another partition to btrfs fails, however  then manually copying the game over is succesfull] so perhaps there's just file corruption along the way...

**Comment by maharmstone** [comment] 2020-05-24 16:39
Thanks. I couldn't replicate this - I tried with two of the Total War games I apparently own on Steam (Rome and Medieval), and they both appeared to work alright, so it's probably not the case that the engine is doing something unexpected.

I suspect the root cause is corruption - what does `btrfs check` say on Linux? I'm presuming you've already verified your installations on Steam - did that redownload anything?

**Comment by Chaython** [comment] 2020-05-25 03:11
Rome kept corrupting, however the other 2 are fully intact.
For some reason three kingdoms is missing BTRFS properties when opening the folder's properties.

Thinking it may be a compression issue:
In the BTRFS properties tab deselecting compress does nothing. Further disabling compress in regedit, copying a directory and deselecting compress in properties, created a compressed copy anyways [it was recompressing, as slow copy speed, high cpu usage] 
I tried downloading again, it again was compressing on write.
![image](https://user-images.githubusercontent.com/6486343/82774649-a7c43b80-9e02-11ea-86e5-45f31785a59d.png)
Again deselecting compress in btrfs properties didn't do anything. Perhaps this is because compression type is set to 3, however compress/force compress is 0 so it should inherently ignore type?

Warhammer and Three kingdoms are much newer and use the same denuvo drm etc, maybe a limitation there.

**Comment by Chaython** [comment] 2020-06-03 08:23
Metro Exodus launched and would crash after the intro cutscenes.
No file corruption - if I copy it to an ntfs partition then launch it, it works fine.
Not denuvo - unless it's left overs. As it's the GOG edition.
[MetroExodus_error_report_200603-082233.zip](https://github.com/maharmstone/btrfs/files/4721892/MetroExodus_error_report_200603-082233.zip)

**Comment by maharmstone** [comment] 2020-06-03 12:27
Thanks. This is even more confusing - I started playing the Steam version of Metro Exodus a few weeks ago, and it was fine. (Well, it was horrendously slow, I think due to Denuvo doing something nefarious, but it didn't crash.)
Could you give me the make and model of your hard disk please?

For compression, I suspect that you have the compression checkbox ticked for F:\Games\steamapps, and/or its downloading subdirectory. Try unticking that.

**Comment by Chaython** [comment] 2020-06-03 22:17
Ya \games\ was set to compress.
Is there anyway to force uncompress? Deselecting compression on the folder doesn't decompress.
Need to boot into linux and use "btrfs filesystem defrag"?
The drive is ASX8200NP-960GT-C

**Comment by maharmstone** [comment] 2020-06-05 01:46
I _think_ that once the flag is set on the parent directory, if you create a copy of the children within it the copies won't be compressed.

I wonder if your crashes might be due to a sector size issue. I had to work around a similar issue in Dreamfall a while back, where its sound engine would crash because it naively assumed that hard disks would only ever have 512-byte sectors.

**Comment by ticpu** [comment] 2020-07-04 00:00
I can confirm having the same problem with another Unity game, I did copy the file on NTFS and it worked just fine, then I tries creating a new folder with compression unchecked, copied the content, and the game started no problem thereafter.

I'll have to take a deeper look in whatever is causing that, but it sure seems to be related to the fact it can't get the right file size. Is it because WinBtrfs reports compressed file size by default?  On Linux, there's a special ioctl to get compressed file size instead, all normal commands just report the normal file size.

**Comment by GeorgeGhost** [comment] 2020-07-30 00:11
I've ran into that issue too with HITMAN 2, I had the /games/ subvolume compressed, I moved it to the uncompressed subvolume on linux and that solved the issue.

**Comment by maharmstone** [comment] 2020-08-08 22:47
Thanks all for your help in sorting this - it was indeed an issue with decompression. When memory mapping - such as when loading an EXE - Windows sometimes likes to use dummy pages, which was confusing the compression libraries.

Fixed by https://github.com/maharmstone/btrfs/commit/62dc49a066643c67eb5ebf54c195f60d81b23e1c

**Closed by maharmstone** 2020-08-08 22:47 UTC

**Comment by itsTyrion** [comment] 2021-01-31 21:44
> 
> 
> Thanks all for your help in sorting this - it was indeed an issue with decompression. When memory mapping - such as when loading an EXE - Windows sometimes likes to use dummy pages, which was confusing the compression libraries.
> 
> Fixed by [62dc49a](https://github.com/maharmstone/btrfs/commit/62dc49a066643c67eb5ebf54c195f60d81b23e1c)

So you can now use FS compression without games crapping themselves?

**Comment by maharmstone** [comment] 2021-01-31 21:45
That's right
