### ISSUE TITLE
I don't see volume in explorer or partition manager

### ISSUE THREAD

**Issue by mlunax** [maharmstone/btrfs#210] opened 2019-11-08 21:50 UTC
I am using Windows 10 (Version 10.0.18362 Build 18362) and after install driver I see it in device manager and regedit but I don't see a volume (e.g. in explorer).
Thanks in advance for any help.

**Comment by MegaZeroX10** [comment] 2019-11-08 21:53
Do you have a disk already formatted as BTRFS?

**Comment by mlunax** [comment] 2019-11-08 23:08
Yes

**Comment by MegaZeroX10** [comment] 2019-11-09 16:43
Is the Btrfs controller showing in Device Manager with no exclamation point?

**Comment by mlunax** [comment] 2019-11-10 11:45
Yes, there it is. Without any problem (reported by Windows).

**Comment by MegaZeroX10** [comment] 2019-11-10 21:14
Weird. Please try the new release and see if that fixes it.

**Comment by BenNottelling** [comment] 2019-11-11 05:05
I'm afraid @MegaZeroX10 doesn't really know how to help here. 

If you don't see it in this menu (as an unknown file system or as BTRFS) then your computer likely isn't seeing the drive
![image](https://user-images.githubusercontent.com/17304943/68562014-c467cb80-03fc-11ea-91c8-880612a0ae69.png)
My only other suggestion is to open `diskpart`, type `list disk`, then plug your device in, and then list the devices again. If you don't see another one pop up, there's an issue between the computer and the drive that is not related to the driver.
Note: if it's a SATA drive, make sure you have hot swapping on before you plug it in, or plug it in with the computer off.

**Comment by mlunax** [comment] 2019-11-11 15:13
I can see it in diskmgr. 
Every partition is blank in FS column.

**Comment by MegaZeroX10** [comment] 2019-11-11 15:13
I'm experiencing this problem in Windows Server 2003 when using v1.5. The Disk with the BTRFS partition shows up in Disk Management but I can't assign a drive letter to it (no dialog box shows when I try to do it).

**Comment by MegaZeroX10** [comment] 2019-11-29 03:40
The same issue occurs in Windows 7 but the driver is able to assign a drive letter to the partition.

**Comment by damian101** [comment] 2020-03-08 02:50
I have the same issue on one of my systems and it only affects SATA and Nvme drives, Btrfs partitions on USB drives work fine. I also tried older versions of WinBtrfs, but that didn't fix it.

**Comment by damian101** [comment] 2020-03-08 03:08
Btrfs partitions on the virtual drive from my RAID controller are also not recognized. The RAID controller doesn't cause this problem, the issue persists when I remove it.
I will try a fresh Windows installation on the same machine when I have the time.

**Comment by ale5000-git** [comment] 2020-03-08 14:47
The version 1.7 had some problems, try with 1.7.1

**Comment by damian101** [comment] 2020-03-08 14:55
@ale5000-git I did. I just tried 1.7 and 1.6 after 1.7.1 failed, to see if they maybe work.

**Comment by maharmstone** [comment] 2020-03-11 11:48
@damian101, what's your RAID controller? Is this hardware or software RAID?

**Comment by damian101** [comment] 2020-03-12 02:34
@It's a hardware raid controller, Fujitsu D3116, with the LSI SAS 2208 ROC.

**Comment by MegaZeroX10** [comment] 2020-03-22 22:25
> 
> 
> I'm experiencing this problem in Windows Server 2003 when using v1.5. The Disk with the BTRFS partition shows up in Disk Management but I can't assign a drive letter to it (no dialog box shows when I try to do it).

I tried using v1.7.1 and am still having the issue being mentioned. I also get a "DiskPart could not assign the drive letter or mount point. Make sure the drive letter or mount point is valid." when I try assigning a drive letter using DiskPart.

**Comment by damian101** [comment] 2020-04-01 08:50
After having the first BSOD described in #246 all the Btrfs partitions now show up, including the Btrfs partition on the virtual drive of my hardware RAID controller.

**Comment by ElpizoZ** [comment] 2020-05-28 17:20
Maybe this will fix the issue being discussed:

https://support.citrix.com/article/CTX122143

**Comment by chevcheli0s** [comment] 2020-12-17 21:42
I have same issue.
On Thinkpad 10 tablet with eMMC. One part is ntfs(windows 10) and the second is btrfs.
 
> Open a Command Prompt ran as Administrator.
Run diskpart.
Type automount enable and press Enter.
Type exit and press Enter.
Close the Command Prompt<
This suggest doesn't work

Properties in the menu are not active.
<img width="798" alt="screen" src="https://user-images.githubusercontent.com/48658076/102546578-eb490480-40c8-11eb-93e2-70a85cc73450.PNG">

Also I have same issue on my laptop with nvme samsung 970 evo.

**Comment by Mek101** [comment] 2021-01-23 20:28
> 
> 
> Maybe this will fix the issue being discussed:
> 
>     1. Open a Command Prompt ran as Administrator.
> 
>     2. Run diskpart.
> 
>     3. Type automount enable and press Enter.
> 
>     4. Type exit and press Enter.
> 
>     5. Close the Command Prompt window.

Didn't work here on Widnows 10 1909 build 18363.1316

**Comment by sryze** [comment] 2021-11-06 09:52
Same issue on Windows 7. I converted an EXT4 partition to BTRFS via btrfs-convert on Linux and it's not showing up on Windows. But before this, I've tried with a removable USB drive formatted to BTRFS and it worked flawlessly.

**Comment by Vixtron** [comment] 2021-12-31 12:01
Same issue occurred to me after I disabled CSM and enabled secureboot via bios, I suspect it was caused by the signed btrfs driver.

**Comment by Vixtron** [comment] 2021-12-31 12:39
> Same issue occurred to me after I disabled CSM and enabled secureboot via bios, I suspect it was caused by the signed btrfs driver.

Confirmed fixed with secureboot enabled by writing the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy` DWORD -> UpgradedSystem VALUE -> 1

**Comment by Jibaru** [comment] 2022-01-31 16:40
> Maybe this will fix the issue being discussed:
> 
> 1. Open a Command Prompt ran as Administrator.
> 2. Run diskpart.
> 3. Type automount enable and press Enter.
> 4. Type exit and press Enter.
> 5. Close the Command Prompt window.

This work for me on Windows 8.1

**Comment by maharmstone** [comment] 2023-11-30 01:51
Closing old issues

**Closed by maharmstone** 2023-11-30 01:51 UTC

**Comment by IlgazC** [comment] 2024-01-12 20:24
> Maybe this will fix the issue being discussed:
> 
>     1. Open a Command Prompt ran as Administrator.
> 
>     2. Run diskpart.
> 
>     3. Type automount enable and press Enter.
> 
>     4. Type exit and press Enter.
> 
>     5. Close the Command Prompt window.

It is tragi-comic that in 2024 with such a mature, stable code, MS Windows 10 (not winbtrfs) randomly turns off that automount and you are stuck completely clueless staring to screen wondering why BTRFS drive with 1TB of data doesn't show up. Especially when you are messing with Gentoo Linux install :-)

@maharmstone I can't really ask a deep level system driver developer to fiddle with UI etc but, is there a chance to check this issue deeper if we provide all the information etc? I suspect Windows 10 core however it won't likely get anything except security updates. I don't want you or anyone to hack/patch crazy things to fix _their_ bug, but there must be something to do. For example, a command/registry key user can change so that automount setting sticks. 

Gentoo made me enter many fdisk etc interaction and I almost had heart-attack when I saw drive missing (I obviously back it up to gdrive via duplicati) . A less experienced user can seriously panic.

**Comment by yoboujon** [comment] 2025-04-29 20:14
> > Same issue occurred to me after I disabled CSM and enabled secureboot via bios, I suspect it was caused by the signed btrfs driver.
> 
> Confirmed fixed with secureboot enabled by writing the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy` DWORD -> UpgradedSystem VALUE -> 1

Thanks a lot, worked for me !! I forgot I enabled Secure Boot, while I did signed all my entries, it seems that the disk was blocked by it, changing this registry value did the trick after a reboot!
