### ISSUE TITLE
Cannot pin two folders to quick access.

### ISSUE THREAD

**Issue by atbug** [maharmstone/btrfs#217] opened 2019-12-08 05:51 UTC
It seems that I cannot pin two folders in the btrfs drive to quick access.

How to reproduce this:
(1) choose one folder in the btrfs drive, right click and choose pin to quick access.
(2) choose another folder in the same drive and pin to quick access.

The second folder never appears.

**Comment by ale5000-git** [comment] 2019-12-08 13:47
This bug was already fixed, what version of WinBtrfs do you have installed?

**Comment by mistguy** [comment] 2019-12-08 16:33
WinBtrfs Version 1.5 with Windows 10 1909.

**Comment by ale5000-git** [comment] 2019-12-08 16:35
Strange, it should be the same problem of #101

**Comment by mistguy** [comment] 2019-12-08 16:36
So can you reproduce this? If not I'll close this issue and look into other problems.

**Comment by ale5000-git** [comment] 2019-12-08 16:41
I'm not the author of WinBtrfs, I'm just trying to help.
I think you should leave it opened, and list the exact steps one by one to be able to reproduce it.

**Comment by bsulyok** [comment] 2021-07-07 12:02
I experience this issue today with the latest release, either it wasn't fixed in #101 or the bug was reintroduced since then!

**Comment by Koppajin** [comment] 2021-11-29 04:20
I'm experiencing this. Windows 10 21H2 using the latest release of this.

**Comment by 13xforever** [comment] 2022-08-31 19:26
This is still happening. Also the single pinned folder will randomly change to some other folder, usually after reboot, but often enough while you use the PC.

**Comment by maharmstone** [comment] 2023-11-30 01:56
Closing old issues

**Closed by maharmstone** 2023-11-30 01:56 UTC

**Comment by jroyvde** [comment] 2024-03-10 23:37
Can this be reopened? I'm experiencing this on version 1.8.2. In addition, the pinned folder seems to randomly change to a different one every so often, usually one I have accessed recently but never actually pinned.

**Comment by Belkovinov** [comment] 2024-10-01 10:23
I have the same issue on Windows 11
