### ISSUE TITLE
File Names With and Without Caps are not Different

### ISSUE THREAD

**Issue by sergiorgb** [maharmstone/btrfs#477] opened 2022-04-18 23:00 UTC
I had a drive with two Folders "home" and "Home", when i used explorer to get into "Home" it showed up the contents of "home" instead of "Home", i also used cd and it didnt work so it should be a winbtrfs issue

**Comment by maharmstone** [comment] 2022-04-19 00:42
Not a bug, this is how Windows operates. If you have two files differing only in case, and the parent directory isn't marked as case-sensitive, it's arbitrary which one you get.

If you're using Windows 10, you should get better results if you set the case-sensitive flag using `fsutil`.

**Closed by maharmstone** 2022-04-19 00:42 UTC
