### ISSUE TITLE
Run As Administrator may not work. 

### ISSUE THREAD

**Issue by jarrard** [maharmstone/btrfs#526] opened 2022-10-01 14:50 UTC
On my Windows 11 system when I attempt to run a exe as administrator I get a weird Windows cannot access error message.  Is this functionality just not supported?

Network path error code 0x800704b3

**Comment by maharmstone** [comment] 2022-10-01 15:56
Duplicate of https://github.com/maharmstone/btrfs/issues/519

**Closed by maharmstone** 2022-10-01 15:56 UTC
