### ISSUE TITLE
Cannot create directories in WSL when case=dir (BTRFS on vhdx)

### ISSUE THREAD

**Issue by kde99** [maharmstone/btrfs#216] opened 2019-12-02 10:14 UTC
Hello everyone. 

I wanted to try out this driver so I created a virtual disk (VHDX type, expanding, 2GB max size) and added one partition to it (primary 2GB size) then formatted to BTRFS using ".\mkbtrfs.exe P:" which went well. 

After that it is mounted I can copy in explorer and use it but from wsl I cannot create directories as it says `mkdir: cannot create directory ‘/mnt/e/a’: Input/output error` everytime I use mkdir. It works in explorer, also I can use touch to create files. Default mount options are `E:\ on /mnt/e type drvfs (rw,noatime,uid=1000,gid=1000,metadata,case=dir)` and it also doesn't work with `E: on /mnt/e type drvfs (rw,noatime,metadata,case=dir)` 

BUT when case=off it works and it creates the directory. The only problem with that is that I want to enable case sensitivity for all the sub folders too. Is there anything I can do to make it work or is this a limitation of the driver?

Driver: latest 1.5
Windows: Windows 10 Pro 1903 Build 18362.476
WSL: Ubuntu eoan (latest) installed from store then upgraded using do-release-upgrade
wsl.conf is what the README says + options = "metadata,case=dir"

Thank you for your help!

**Comment by maharmstone** [comment] 2019-12-02 20:23
Thanks for reporting this. Yes, you're right - I can reproduce it on Windows 1809.

It looks like it might be something to do with the passthrough of POSIX permissions - if you do it as root it gets slightly further, returning "Input/Output error" rather than "Access denied". I'll look into it.

**Comment by kde99** [comment] 2019-12-03 06:11
Thanks! Well it might not be a complete failure to do that since I can do both chown and chmod and those are preserved since I was getting that error from the user account without sudo and ls confirms those changes.

**Comment by maharmstone** [comment] 2020-02-26 23:19
This is fixed in version 1.7.

**Closed by maharmstone** 2020-02-26 23:19 UTC
