### ISSUE TITLE
Memory leak occurring when using the attached batch file

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#175] opened 2019-08-23 20:55 UTC
When I used the attached batch file in a 64-bit Windows 7 VM (that has a 32 GB NTFS partition and a 9 GB BTRFS partition with 2 GB of RAM assigned to it) and a 64-bit Windows 10 VM (that has a 32 GB NTFS partition and a 8 GB BTRFS partition with 2 GB of RAM assigned to it), the RAM usage shown in Task Manager kept going up until I got CRC errors. I am attaching it and a video of the RAM usage going up.

[leak.zip](https://github.com/maharmstone/btrfs/files/3536162/leak.zip)
[Windows 7 running Leak Test.zip](https://github.com/maharmstone/btrfs/files/3536171/Windows.7.running.Leak.Test.zip)
[Windows 10 running Leak Test.zip](https://github.com/maharmstone/btrfs/files/3536446/Windows.10.running.Leak.Test.zip)

**Comment by maharmstone** [comment] 2019-08-24 00:07
Duplicate of https://github.com/maharmstone/btrfs/issues/164, which has been fixed.

**Closed by maharmstone** 2019-08-24 00:07 UTC
