### ISSUE TITLE
Issue with using TortoiseGit on a BTRFS formatted drive

### ISSUE THREAD

**Issue by ElpizoZ** [maharmstone/btrfs#263] opened 2020-05-27 20:19 UTC
When I use TortoiseGit to clone a repository to a BTRFS formatted drive, I am getting errors (such as "Rename from 'F:/reactos/.git/index.lock' to 'F:/reactos/.git/index' failed. Should I try again?" and "error: inflate: data stream error (incorrect data check)". The first one occurs when reverting a cloned repository after closing the Git Clone dialog box. The second one occurs while cloning it. The repository being cloned is https://github.com/reactos/reactos.git. The version of the BTRFS driver that is being used is 1.7.3 and the OS is Windows 7 x86.

**Comment by maharmstone** [comment] 2020-05-28 00:28
I've just tested this on Windows 10, and it works fine. You're not filling up the drive, are you? And are you certain that when you wrote "Windows 7", it wasn't a typo for "ReactOS"?

**Comment by ElpizoZ** [comment] 2020-05-28 02:33
1. Its an 8 GB VHD formatted as BTRFS that I am using.
2. No.

**Comment by maharmstone** [comment] 2020-05-30 12:57
Closing as can't reproduce.

**Closed by maharmstone** 2020-05-30 12:57 UTC
