### ISSUE TITLE
Operation not allowed in WOW64

### ISSUE THREAD

**Issue by coralhl** [maharmstone/btrfs#336] opened 2020-12-31 07:33 UTC
I have a problem installing the driver on Windows 10 build 19042.685.
Probably this is due to something wrong in the "inf" file.

**Comment by ticpu** [comment] 2020-12-31 09:04
There's a serious lack of information in this issue.

**Comment by coralhl** [comment] 2020-12-31 13:29
> There's a serious lack of information in this issue.
The only message i got during installation is 'Operation not allowed in WOW64'
Files were copied to the System32 and SysWOW64 folders, but 32 bit version, and the service is missing.
How can i provide more information?

**Comment by maharmstone** [comment] 2020-12-31 15:52
I've no idea what you're doing here - you should right-click the INF and choose Install, and it'll copy the binaries to System32. If you're on amd64, it'll ignore the 32-bit versions entirely (i.e. nothing will get copied to SysWOW64).

> Windows 10 build 19042.685

Is this a beta version? Microsoft have been known to break things like this in the betas, only for them to be fixed by the time the proper release comes around.

**Comment by ticpu** [comment] 2021-01-02 01:33
> Is this a beta version? Microsoft have been known to break things like this in the betas, only for them to be fixed by the time the proper release comes around.

In this case, 19042.685 is the latest version aka 20H2.  I currently use WinBtrfs on this version of Windows too but it was upgraded.

**Comment by badsectoracula** [comment] 2021-11-15 12:18
In case someone has this issue, it might be due to using some other file manager than Explorer. I got this error when i tried to install the driver via Total Commander but doing it via Windows Explorer worked fine.

**Comment by ale5000-git** [comment] 2021-11-21 20:50
If you invoke the INF from a 32-bit app then System32 will be redirected to SysWOW64, it is the intended behaviour of Windows.

**Comment by maharmstone** [comment] 2023-11-30 01:48
Closing old issues

**Closed by maharmstone** 2023-11-30 01:48 UTC
