### ISSUE TITLE
Writing to volume hangs after some time

### ISSUE THREAD

**Issue by dinfinity** [maharmstone/btrfs#58] opened 2017-09-16 09:25 UTC
Whether copying with Total Commander or Explorer, the copying process just stops and becomes non-responding. 

**Additional information:**
It seems to happen at the end of copying a file, i.e. that some files are transferred without issue, but then all of a sudden the copying stops. I tested this with different files, so the source does not seem to be the problem.
The copying processes (either Total Commander or Explorer) are not killable ('access denied' in task manager). When trying to restart, the processes are noted as preventing restart. 'Restart anyway' continues but leads to a spinner spinning for at least 3 minutes (after which I performed a hard reset). If my knowledge of such behavior is correct, this is generally an indicator of the processes waiting for a kernel space component.

**System information:**
Winbtrfs 1.0
Windows 10 Pro
Build 15063.rs2_release.170317-1834
Volume is a ~2,9GB partition on a GPT drive, created with mkbtrfs.exe. The first partition on that drive is a 30GB Linux (swap) partition.

I will update this issue later with information from DebugView and the logs.

**Comment by dinfinity** [comment] 2017-09-16 11:19
BTRFS Log is attached. DebugView log file was empty, alas. No messages were generated during the hanging process, however.

There are three sessions in the BTRFS log:

The first one is with DebugLogLevel set to 3. This crashed / hung Explorer in a bad way and I needed to temporarily disable the driver via a commandline boot to be able to get to a working install again. Note that I did not get to copying to the volume.

The second one is a session with DebugLogLevel set to 2. I _did_ copy files here and I did experience the hanging behaviour.

The third one is a session prior to me uninstalling the btrfs driver (for now).

Final addition: The hanging behaviour _seems_ to occur with larger files, although files of 10GB and up have been copied successfully to the volume.

[btrfs.log.zip](https://github.com/maharmstone/btrfs/files/1308264/btrfs.log.zip)

**Comment by dinfinity** [comment] 2017-09-16 11:22
BTW: The readme could be a bit clearer about how to switch to the debug drivers. Just 'copy the files in Debug\x64 or Debug\x86 into x64 or x86' is not enough, as this will not replace btrfs.sys in Windows\System32\drivers.

**Comment by maharmstone** [comment] 2017-10-15 19:47
Hi, could you try the version I've just released please? It squashes a nasty deadlock bug, hopefully it's the same one!

**Comment by dinfinity** [comment] 2017-10-16 10:24
Quick update: 

I left the volume unchanged and the new driver does not seem to recognize it at all. When opening Disk Management, the associated drive letter is not shown (it *is* shown in the file explorer as 'Local Disk (D:)'). If I then try to change the drive letter and path, the following is shown:
![image](https://user-images.githubusercontent.com/4126535/31607458-b05565d2-b26c-11e7-9a40-55a364dcc776.png)

Refreshing as instructed does not change anything.

Note that I did not enable Windows testing mode, as the new drivers are signed.

**Comment by dinfinity** [comment] 2017-10-16 13:07
Update:
The copying process seemed to go well initially, but at 1% of copying 1.2TB of video files the exact same issue occurred.

**Comment by tmteamz** [comment] 2017-10-31 16:13
It's slowing down then hangs
https://i.imgur.com/xm9S5Cb.png

**Comment by aubade** [comment] 2017-12-12 13:44
Getting the same problem. It doesn't seem to ~corrupt~ data, it just freezes and stops being able to access the partition.

**Comment by JSchoeck** [comment] 2018-04-25 07:53
This happens to me too. I have no prior experience with BTRFS and I created my BTRFS volume on an external USB disk using NextcloudPi, so it's a bit of a black box to me.
When copying my data from my Windows 10 PC to this external USB drive the copying procedure will start without a problem, but fail at any random point. It has failed before even copying a single file, it successfully copied severl Gb - I have not noticed any properties of the files that could lead to this failure.

I'm afraid this might happen on Linux with my RasPi, too or to loose data eventually...
Do you guys think BTRFS is ready for production and as long as I copy everything (with a bunch of restarts) I will be fine?

**Comment by maharmstone** [comment] 2018-04-25 08:39
Any problem is definitely with my driver and not the filesystem itself!

**Comment by JSchoeck** [comment] 2018-04-25 08:42
Would it help if I created logs or do you not really have time to work on the driver right now anyway?

**Comment by maharmstone** [comment] 2018-04-25 08:44
If it's deadlocking, which it sounds like, unfortunately logs won't help...
I'll try and reproduce the issue when I get the chance.

**Comment by Starz0r** [comment] 2018-05-04 04:32
I'm getting the same issue when I didn't before. I'm almost sure that is has something to do with Windows Updates either changing or removing something this driver relied on? @JSchoeck @aubade @tmteamz @dinfinity Does the issue still occur if you uninstall the driver and then reinstall it? Despite this issue being created in 2017, I feel like it has to be a issue with Window's update process.

OS: Windows 10
Ver: 1709 (Build 16299.371)

**Comment by maharmstone** [comment] 2018-05-12 13:01
@Starz0r, I think you're right - I've been able to get it to crash now, in circumstances where it definitely didn't before. My crash is caused by Windows passing a Btrfs handle to fastfat's FatFsdCleanup - I'm not sure why it'd be doing that...

**Comment by elliotclee** [comment] 2018-09-07 00:49
I'm running into this problem too. Tried copying about 70G of files from an NTFS volume to two different BTRFS volumes - hung both times after 8-10G transferred. The second btrfs volume is on a scratch drive and can be reformatted if you want me to test anything. WinBtrfs-1.0.2, Windows 10 build 17134.228 (version 1803).

**Comment by Zero3K** [comment] 2018-09-08 02:04
I am also experiencing this issue when using the latest version of it on a 64-bit Windows 10.

**Comment by Zero3K** [comment] 2018-09-14 20:59
Any news?

**Comment by Extravert-ir** [comment] 2018-09-15 00:48
Do anybody have a way to reliably reproduce this bug?

**Comment by Starz0r** [comment] 2018-09-15 01:02
@Extravert-ir Transfer a lot of NTFS tagged files into a BTRFS formatted drive. The payload should be around 1GB or more.

**Comment by Zero3K** [comment] 2018-11-21 18:59
I wonder if this has been fixed because of the recent changes.

**Comment by elliotclee** [comment] 2019-01-20 17:30
I just tried with winbtrfs-1.1.

The first time I did a copy of 50G of assorted files and at the same time had 7zip extract an archive into the directory. The system didn't hang but after a while the FS remounted itself as readonly.

After rebooting, before I did anything interesting, I use DbgView to see a bunch of DbgPrint's that look like:
....
Btrfs ERR : insert_tree_item : error: key (14caebb6000,a9,0) already present
Btrfs ERR : insert_tree_extent_skinny : insert_tree_item returned c00000e5
....

Then I did a dd of 40G of nul's and it didn't cause any problems. 

Then I did another copy of 50G of assorted files and got a few of:
....
Btrfs ERR : file_create : create_stream returned c0000022
...
but things kept on copying and finished successfully.

Then I had 7zip extract that same archive into the same place and it completed successfully.

I suspect that I stumbled on another bug, but I would be prepared to call this particular bug fixed as of 1.1.

**Comment by EterniaLogic** [comment] 2020-01-17 15:02
1. Open Steam, Download or verify something. (Steam uses cross-thread pipes, could cause CopyOnWrite problems)
2. Open Windows Explorer on drive and right click properties to force a hook.

With these two applications open at the same time, causes a long hang.

**Comment by maharmstone** [comment] 2020-01-17 16:09
Are you using compression?

**Comment by EterniaLogic** [comment] 2020-01-18 10:59
Yes, zstd:15 compression.

**Comment by Atemu** [comment] 2020-01-19 14:02
ZSTD 15 is pretty CPU and memory intensive and I assume WinBtrfs blocks userspace until a write transaction is done; what's CPU(, RAM) and IO usage like while reproducing the bug?

**Comment by maharmstone** [comment] 2020-01-19 21:16
The few MB a second from a download shouldn't tax any compression algorithm on a modern CPU, you'd think...

I can't reproduce this on my Steam volume (two disks in RAID0). What do you mean by "single mode on a 10 multi-drive" - you've got ten disks on your Btrfs volume, but aren't using RAID? Or do you mean that your disks are exposed via some kind of underlying device?

**Comment by BlueAmulet** [comment] 2021-01-07 08:15
Just converted a NTFS partition of mine to BTRFS, and after copying more than 100GiB to the drive without fail, it got to a large 4GB file and then completely hung, with Explorer saying "more than one day" for the ETA. I ran [Sync](https://docs.microsoft.com/en-us/sysinternals/downloads/sync) cause I was going to try and reboot/reset the computer and wanted to get disk caches flushed if possible, and suddenly the computer became completely responsive again and the copy continued and finished.

**Comment by maharmstone** [comment] 2023-11-30 01:45
Closing old issues

**Closed by maharmstone** 2023-11-30 01:45 UTC
