### ISSUE TITLE
Random null characters get added while editing files in Obsidian

### ISSUE THREAD

**Issue by blacklightpy** [maharmstone/btrfs#469] opened 2022-03-19 16:46 UTC
I used to take notes in Obsidian, and for dual booting, I moved my vault to a Btrfs partition. But while I'm editing a file in that partition, after a while a message pops up saying file was modified outside the editor, and a bunch of null characters get appended to it. This was not an issue when the files were in NTFS.

![image](https://user-images.githubusercontent.com/28739146/159130256-de740ba4-7505-47a6-9216-7570bd663f9e.png)

It should be noted that Obsidian has the ability to load external changes in real-time. I also posted a bug report in Obsidian forums (https://forum.obsidian.md/t/a-stream-of-null-characters-are-added-to-the-end-of-file-while-editing/32913), but I think this could be a WinBtrfs issue.

**Comment by maharmstone** [comment] 2022-03-19 18:25
Thanks. I'm fairly sure this is a driver issue, as there's a very similar issue somewhere here, which I wasn't able to replicate. I'll see if I have more luck with Obsidian.

**Comment by alex4401** [comment] 2022-03-31 18:43
Having the same issue with Unreal Engine project definition files (.uproject, text file with JSON) if they're small (mine's around 408 bytes, completely fresh) after the second write.
![image](https://user-images.githubusercontent.com/33527044/161127098-701deb90-5876-4efe-b3cc-911aef0be3c9.png)

**Comment by blacklightpy** [comment] 2022-06-29 14:57
I figured out one thing about the added characters - I created a text file and typed in 6 characters, and then cleared the contents but then 7 bytes of null characters got added to the empty page. I think the size of the null characters appeded has a relation to the last known size of the text file..

**Comment by maharmstone** [comment] 2022-06-29 17:34
I'm not able to reproduce this in Obsidian v0.14.15. Are you using compression?

>I figured out one thing about the added characters - I created a text file and typed in 6 characters, and then cleared the contents but then 7 bytes of null characters got added to the empty page. I think the size of the null characters appeded has a relation to the last known size of the text file..

It sounds to me that either Obsidian is deciding not to truncate the file, or it's trying and failing. But as it's not open-source, it's difficult to know precisely what it's doing.

**Comment by blacklightpy** [comment] 2022-06-30 03:07
I don't know if I'm using compression, but I don't think I've set it if it was the default option, I'll have to check it.

> It sounds to me that either Obsidian is deciding not to truncate the file, or it's trying and failing. But as it's not open-source, it's difficult to know precisely what it's doing.

It's not only when I clear the file, it also gets appended when I'm writing long notes and then the number of null characters is very huge. I just happened to see it early on and found a correlation between the length of the string and the last word I typed.

**Comment by DavidRockin** [comment] 2022-07-27 09:17
I've been using this driver for over a year (thank you so much btw 💙), and recently after a fresh reinstall I've decided to use this more extensively.

I have a subvolume `projects` for various dev projects. And I've been experiencing this exact issue with Unity, where builds will fail or break Visual Studio project files (*.sln, *.csproj) because of these null bytes.

I first noticed this issue with our multiplayer C# server, which writes to a local JSON config file; which would also cause the server to fail because Newtonsoft (C# JSON library) doesn't know what to do with the null bytes. I've had to add a temp hack to the server to force UTF-8, and remove BOM and null bytes before parsing.

I also noticed the server config was exactly 4096 bytes. And adding my hack reverted it to the normal size ~816 bytes. Could this possibly be related to block sizes?

The original compress was LZO, but I experienced another issue but now I'm using Zstd.

I'll run some tests to see if I can reproduce this faster, and if it persists without compression.

**Comment by maharmstone** [comment] 2022-07-27 22:07
Thanks Dave.

> I also noticed the server config was exactly 4096 bytes. And adding my hack reverted it to the normal size ~816 bytes. Could this possibly be related to block sizes?

Yes, I think so - it looks like it's writing the full sector but then not truncating the file to its actual size.

One thing that has just occurred to me is that it might be caused by a filter driver doing something unexpected. Would you mind pasting the output of `fltmc filters`?

**Comment by DavidRockin** [comment] 2022-07-27 23:07
Here's the output of that

```
Filter Name                     Num Instances    Altitude    Frame
------------------------------  -------------  ------------  -----
bindflt                                 1       409800         0
FsDepends                              13       407000         0
WdFilter                               13       328010         0
storqosflt                              1       244000         0
wcifs                                   2       189900         0
gameflt                                 8       189850         0
CldFlt                                  0       180451         0
FileCrypt                               0       141100         0
luafv                                   1       135000         0
npsvctrig                               1        46000         0
Wof                                     8        40700         0
FileInfo                               13        40500         0
```

**Comment by DavidRockin** [comment] 2022-07-28 01:08
Okay, so I whipped up a quick test program in C# just to remain consistent with my issues. Fundamentally it'll generate a bunch of files with varying sizes, attempt to overwrite them with new varying sizes.

https://github.com/DavidRockin/test-btrfs-files

I've tested all compression algorithms available, even turning it off, and testing disabling COW as well for each test. And unfortunately it seems pretty consistent with generating extra NULL bytes. It likely appears to be some sort of issue whenever the file is overwritten with a different file size, and it generates `n` number of NULL bytes that is always below `4096` bytes. Example if the file size was `7451` bytes, then there are an extra `741` null bytes to make the file size `8192` bytes

I've attached a little snippet of the output log.

Since this was tested in a folder with altered compression/COW settings, and all generated files seem to respect the options, I'll run another test on a new subvolume and have the files save there to see if it's dependent on the current subvolume? I'll also run some tests altering the file encoding and see if that has any impact.

Please let me know if you have any other suggestions on things to test or look into.

[test btrfs.log](https://github.com/maharmstone/btrfs/files/9204457/test.btrfs.log)

**Comment by maharmstone** [comment] 2022-08-08 23:24
Thanks Dave, this helped me to diagnose it. It turns out that the NT kernel apparently sends us spurious commands on occasion, and you just need to know when to ignore them...

This should be fixed by https://github.com/maharmstone/btrfs/commit/d659713464a327f1284b22fdc0f464f530b687c7.

**Closed by maharmstone** 2022-08-08 23:24 UTC
