### ISSUE TITLE
Cannot run exe as administrator, error 0x800704b3

### ISSUE THREAD

**Issue by noradtux** [maharmstone/btrfs#548] opened 2023-01-07 20:37 UTC
On none of my btrfs volumes it is possible to start a program as administrator, i.e. right click on file in Explorer and choose "Run as administrator". I get an error box saying "Network Error" and "Windows cannot access $tool". 
I can run the file normally, I can also run the file from an administrative shell.
<img width="311" alt="Capture" src="https://user-images.githubusercontent.com/1566306/211169415-904fcae5-7024-42a5-8ba5-b3e8da1881c4.PNG">
Doing the same things on a NTFS volume works as it should.
I checked ACLs, the look unsuspicious.

System is Win10 22H2 x64, WinBtrfs 1.8.1

**Comment by maharmstone** [comment] 2023-01-09 01:38
This is a duplicate of https://github.com/maharmstone/btrfs/issues/519

**Closed by maharmstone** 2023-01-09 01:38 UTC
