### ISSUE TITLE
Memory leak when creating and deleting the created file multiple times

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#122] opened 2018-11-10 21:03 UTC
When I run the attached batch file (which outputs the help command to a help.txt file in the root directory of the BTRFS formatted drive and deletes it and then repeats until its closed) for a few minutes, I get a dialog box stating "help.exe is not a valid Win32 application" or a "bad command or filename" message in the Command Prompt window.

[leak.zip](https://github.com/maharmstone/btrfs/files/2568773/leak.zip)

**Comment by Zero3K** [comment] 2018-11-10 22:57
It looks like its causing a hang in Windows 10 64-bit since after running it for a few minutes, I can no longer open an Explorer window (it hangs when I try to do so).

**Comment by maharmstone** [comment] 2018-11-10 23:12
Again - is your filesystem clean?

**Comment by Zero3K** [comment] 2018-11-11 00:03
I formatted it as BTRFS via ReactOS's text mode setup since I couldn't format as BTRFS it in Windows (it just stated that it failed) and then ran the leak.bat. After a few minutes, instead of hanging the Explorer window I had open and viewing the BTRFS drive, it just ended up crashing the Command Prompt that was running the batch file.

**Comment by Zero3K** [comment] 2018-11-17 18:38
It should be clean since I formatted it under ReactOS.

**Comment by jeditobe** [comment] 2018-11-20 09:01
@Zero3K  it should be but it may be not. And we need to know is it clean in your case after format operation under ReactOS.

**Comment by Zero3K** [comment] 2019-08-03 18:23
Please make the file system checking tool available for Windows so I can run it.

**Comment by Zero3K** [comment] 2019-08-04 20:51
I ran btrfs check twice after formatting a VM's disk image as BTRFS when installing ReactOS. Here are the screenshots of the results:

![VirtualBox_ReactOS (fresh install before running the leak batch file)](https://user-images.githubusercontent.com/6194332/62429076-fcfa5980-b6d7-11e9-8eb0-9a29d007fc1b.png)
![VirtualBox_ReactOS (fresh install after running the leak batch file)](https://user-images.githubusercontent.com/6194332/62429080-0a174880-b6d8-11e9-9227-e9dddede0186.png)

**Comment by maharmstone** [comment] 2019-08-04 21:11
I'm going to close this issue as it involves ReactOS. As I've told you on multiple occasions, I only accept bug reports for Windows.

**Comment by Zero3K** [comment] 2019-08-04 21:11
Well, the issue also occurs on Windows.

**Closed by maharmstone** 2019-08-04 21:11 UTC

**Comment by Atemu** [comment] 2019-08-04 23:09
Or you just leave out ReactOS entirely because if the filesystem is ever touched by it that might be what's causing the issue.

The issue needs to be reproducible on Windows and Windows only.
