### ISSUE TITLE
btrfs for windows filesystem on a single drive not showing

### ISSUE THREAD

**Issue by rodneynottrotter** [maharmstone/btrfs#105] opened 2018-08-07 06:01 UTC
hy

i just installed your driver on windows 10. i have a dual boot ubuntu 18.04 / win 10.
i have 3 hard drives in my pc, 2 are raid0 btrfs, and one is a single disk btrfs volume.

the 2 that are in raid0 are visible in windows, but the single volume is not.

i see it under disk management, but there is no btrfs volume on my computer (windows explorer)

here is some info i got about the btrfs volume:

```
sudo blkid | grep 'btrfs'
/dev/sdb: LABEL="DATA" UUID="900ad984-9eee-4521-ac61-11a85c3eedc7" UUID_SUB="1050b6a9-dfc8-42cb-89a9-c8deeb4dbf13" TYPE="btrfs"
/dev/sdc: LABEL="DATA" UUID="900ad984-9eee-4521-ac61-11a85c3eedc7" UUID_SUB="66987b8f-d2eb-449c-8650-ad902dbd442e" TYPE="btrfs"
/dev/sde: LABEL="STORAGE" UUID="3f82de95-b72c-4c87-8dcc-c4dcb865c9f1" UUID_SUB="5a143664-1e1c-424e-a646-e06a549c6aeb" TYPE="btrfs"

STORAGE is not visible under windows, DATA (raid0 2in1) is visible under windows

sudo btrfs-show-super -f /dev/sde
superblock: bytenr=65536, device=/dev/sde
---------------------------------------------------------
csum                    0x52111db9 [match]
bytenr                  65536
flags                   0x1
                        ( WRITTEN )
magic                   _BHRfS_M [match]
fsid                    3f82de95-b72c-4c87-8dcc-c4dcb865c9f1
label                   STORAGE
generation              2655
root                    205651968
sys_array_size          129
chunk_root_generation   2652
root_level              1
chunk_root              20971520
chunk_root_level        1
log_root                0
log_root_transid        0
log_root_level          0
total_bytes             3000592982016
bytes_used              1556776415232
sectorsize              4096
nodesize                16384
leafsize                16384
stripesize              4096
root_dir                6
num_devices             1
compat_flags            0x0
compat_ro_flags         0x0
incompat_flags          0x161
                        ( MIXED_BACKREF |
                          BIG_METADATA |
                          EXTENDED_IREF |
                          SKINNY_METADATA )
csum_type               0
csum_size               4
cache_generation        2655
uuid_tree_generation    2655
dev_item.uuid           5a143664-1e1c-424e-a646-e06a549c6aeb
dev_item.fsid           3f82de95-b72c-4c87-8dcc-c4dcb865c9f1 [match]
dev_item.type           0
dev_item.total_bytes    3000592982016
dev_item.bytes_used     1568761970688
dev_item.io_align       4096
dev_item.io_width       4096
dev_item.sector_size    4096
dev_item.devid          1
dev_item.dev_group      0
dev_item.seek_speed     0
dev_item.bandwidth      0
dev_item.generation     0
sys_chunk_array[2048]:
        item 0 key (FIRST_CHUNK_TREE CHUNK_ITEM 20971520)
                chunk length 8388608 owner 2 stripe_len 65536
                type SYSTEM|DUP num_stripes 2
                        stripe 0 devid 1 offset 20971520
                        dev uuid: 5a143664-1e1c-424e-a646-e06a549c6aeb
                        stripe 1 devid 1 offset 29360128
                        dev uuid: 5a143664-1e1c-424e-a646-e06a549c6aeb
backup_roots[4]:
        backup 0:
                backup_tree_root:       136167424       gen: 2654       level: 1
                backup_chunk_root:      20971520        gen: 2652       level: 1
                backup_extent_root:     96124928        gen: 2654       level: 2
                backup_fs_root:         63520768        gen: 2654       level: 2
                backup_dev_root:        136331264       gen: 2654       level: 1
                backup_csum_root:       136577024       gen: 2654       level: 2
                backup_total_bytes:     3000592982016
                backup_bytes_used:      1556776415232
                backup_num_devices:     1

        backup 1:
                backup_tree_root:       205651968       gen: 2655       level: 1
                backup_chunk_root:      20971520        gen: 2652       level: 1
                backup_extent_root:     205717504       gen: 2655       level: 2
                backup_fs_root:         63520768        gen: 2654       level: 2
                backup_dev_root:        136331264       gen: 2654       level: 1
                backup_csum_root:       223100928       gen: 2655       level: 2
                backup_total_bytes:     3000592982016
                backup_bytes_used:      1556776415232
                backup_num_devices:     1

        backup 2:
                backup_tree_root:       714376183808    gen: 2652       level: 1
                backup_chunk_root:      20971520        gen: 2652       level: 1
                backup_extent_root:     714533126144    gen: 2652       level: 2
                backup_fs_root:         714393337856    gen: 2652       level: 2
                backup_dev_root:        714375741440    gen: 2652       level: 1
                backup_csum_root:       714404397056    gen: 2652       level: 2
                backup_total_bytes:     3000592982016
                backup_bytes_used:      1556776415232
                backup_num_devices:     1

        backup 3:
                backup_tree_root:       714384277504    gen: 2653       level: 1
                backup_chunk_root:      20971520        gen: 2652       level: 1
                backup_extent_root:     714384293888    gen: 2653       level: 2
                backup_fs_root:         714393337856    gen: 2652       level: 2
                backup_dev_root:        714375741440    gen: 2652       level: 1
                backup_csum_root:       714384474112    gen: 2653       level: 2
                backup_total_bytes:     3000592982016
                backup_bytes_used:      1556776415232
                backup_num_devices:     1
```

**Comment by maharmstone** [comment] 2018-08-07 07:16
No idea, sorry - your compat flags are okay. Could you attach a screenshot of diskmgmt.msc please?

**Comment by rodneynottrotter** [comment] 2018-08-07 14:20
![image](https://user-images.githubusercontent.com/42165652/43781336-f144665a-9a5c-11e8-9214-186c6db30843.png)
to this i say cancel. then it loads the volumes:

![image](https://user-images.githubusercontent.com/42165652/43781504-5398baa4-9a5d-11e8-8e04-0c97e8fa8e16.png)

disk3 is the one that doesnt show, while disk1 and disk4 are raid0 and are shown in windows explorer
any other information you need from the properties of disk 3 ?

**Comment by maharmstone** [comment] 2018-11-22 02:19
Duplicate of https://github.com/maharmstone/btrfs/issues/84

**Closed by maharmstone** 2018-11-22 02:19 UTC
