### ISSUE TITLE
Old file's remnant at the end of a text file when it is overwritten.

### ISSUE THREAD

**Issue by HubKing** [maharmstone/btrfs#301] opened 2020-09-27 00:02 UTC
I created a text file on a BTRFS drive on Windows, typed "111111111111111" in Notepad, closed Notepad, opened it again, selected all and deleted it, typed "22222222", saved the file, and then opened it again. But there is trailing remnant of the old file, as if the first one was overwritten by the second one. Is this a bug?

Here is the screen recording: https://imgur.com/a/df9iCFr

**Comment by maharmstone** [comment] 2020-09-27 12:36
Is the file compressed? If it is, I suspect this is a variation of https://github.com/maharmstone/btrfs/issues/277.

**Comment by HubKing** [comment] 2020-09-27 14:44
> Thanks. Is the file compressed? If it is, I suspect this is a variation of #277.

No, I did not manually do any such thing, unless it is compressed by default. I just formatted a USB hard disk to BTRFS using the Disks GUI utility that came with the Mate desktop under Ubuntu 18.04, and connected it to a Windows computer.

**Comment by maharmstone** [comment] 2020-09-27 14:45
What does the Properties page of the file say?

**Comment by HubKing** [comment] 2020-09-27 14:52
> 
> 
> What does the Properties page of the file say?
![image](https://user-images.githubusercontent.com/10900489/94367918-5f07f080-011c-11eb-93cf-937babedfd73.png)

![image](https://user-images.githubusercontent.com/10900489/94367934-7646de00-011c-11eb-8bd6-7a4e13f71db5.png)

**Comment by maharmstone** [comment] 2020-09-27 14:54
Sorry - if you click the "Details" link, it'll tell you whether it's compressed or not.

**Comment by HubKing** [comment] 2020-09-27 14:55
> 
> 
> Sorry - if you click the "Details" link, it'll tell you whether it's compressed or not.

![image](https://user-images.githubusercontent.com/10900489/94368017-ef463580-011c-11eb-8d8e-9adb7de0b620.png)

**Comment by maharmstone** [comment] 2020-09-28 22:58
Thanks. I can reproduce this. Looks like there's been a change in Windows (2004?) - Notepad sets the end of file correctly, but then the lazy writer for some reason sets it back to what it used to be.

**Comment by HubKing** [comment] 2020-09-28 23:03
> a change in Windows (2004?) 

No, the Windows I used was 1809, although I have installed all the updates.

**Comment by maharmstone** [comment] 2020-09-28 23:24
Thanks for reporting this. This is fixed by https://github.com/maharmstone/btrfs/commit/56b5ba700443490bab526523407e7dec8ff5bb73.

**Closed by maharmstone** 2020-09-28 23:24 UTC
